---
title: "Help"
format: html
---

**Are you interested in using oceanographic satellite data in your work but not sure where to start?**

NOAA CoastWatch Satellite Training Courses provide access to environmental satellite data, along with tutorials and example workflows designed to help scientists and resource managers work with these datasests more easily. This website brings together training materials, coding examples, and practical guidance developed through CoastWatch courses to support users with varying levels of experience.

Whether you are new to satellite data or looking for reproducible ways to integrate it into your research or management projects, these resources are intended to help you explore, access, and analyze oceanographic satellite products with confidence.

## Frequently Asked Questions

::: {.faq-section}

::: {.faq}

<details>
<summary>How is the course structured?</summary>

The course combines instructional materials with virtual workshops. 
Instructional materials introduce participants to common types of environmental satellite data including:

- Ocean color
- Sea surface temperature
- Sea surface height
- Salinity
- Ocean surface winds

Workshops focus on practical application where participants recieve individual and group support to:

- Locate online satellite data
- Select data with the spatial and temporal coverage that fits their needs
- Download and work with the data in their preferred software

Most examples focus on R, Python, and ArcGIS, but participants using other software are also welcome.

Participants are encouraged to come with a specific project or question to work on during the workshops.

For example:

- Merging tagged animal tracks with satellite data
- Exploring environmental conditions in a study region
- Preparing satellite data for analysis or visualization
 
Participants tend to get the most out of workshops when they arrive with clear goals, data, or questions in mind. 
</details>

<details>
<summary>Who should take the course?</summary>

The courses are primarily designed for National Marine Fisheries Service and National Ocean Service scientists, but non-NOAA participants are welcome when space is available.

To date, over a thousand participants have taken these courses, including scientists and staff from:

- All six Fisheries Science Centers
- Multiple National Marine Sanctuaries
- Other federal agencies, such as:
  - U.S. Coast Guard
  - U.S. Geological Survey
  - U.S. Fish and Wildlife Service

</details>

<details>
<summary>How much does the course cost?</summary>

There is no fee to participate in the course. Participants are asked to submit a single PowerPoint slide describing the project they worked on during the course. These slides help document course outcomes and shared applications of satellite data.

</details>

<details>
<summary>When and where is the next course?</summary>

The dates and locations of upcoming courses can be found [here](trainings/index.qmd).

To be notified about future courses, contact [Cara Wilson](cara.wilson@noaa.gov).

</details>

:::

:::

## Resources

::: {.resource-grid}


:::{.resource-card}
### CoastWatch Help Desk
The CoastWatch Help Desk provides user support regarding the use of our data products and services. Please do not hesitate to contact us using the methods below:

- Email: coastwatch.info@noaa.gov
- Phone: +1 (301) 683-3335
- [User Forums](https://vlab.noaa.gov/web/coastwatch) (inquiry threads)
:::

:::{.resource-card}
### Training Lectures
Introductory lectures and course materials covering using satellite data.

[View lectures](lectures/index.qmd)
:::

:::{.resource-card}
### Training Tutorials
The training tutorials provide step-by-step guidance for accessing, exploring, and analyzing satellite data, from software setup and data access to coding workflows in Python, R, and MATLAB.

[View training tutorials](trainings/index.qmd)
:::

:::{.resource-card}
### Data Servers
Browse available oceanographic satellite products and datasets on ERDDAP.

- [NOAA CoastWatch West Coast Node](https://coastwatch.pfeg.noaa.gov/erddap/index.html)
- [NOAA CoastWatch East Coast Node](https://coastwatch.noaa.gov/erddap/info/index.html?page=1&itemsPerPage=1000)
- [NOAA CoastWatch Great Lakes Node](https://apps.glerl.noaa.gov/erddap/index.html)
- [NOAA CoastWatch Caribbean and Gulf of America Node](https://cwcgom.aoml.noaa.gov/erddap/info/index.html?page=1&itemsPerPage=1000)
- [NOAA CoastWatch Central Pacific Node]()
- [NOAA CoastWatch PolarWatch Node](https://polarwatch.noaa.gov/erddap/info/index.html?page=1&itemsPerPage=1000)
:::

:::