---
title: "Satellite and Animal Telemetry Data Training"
description: "October 25, 2024, Virtual 10am - 5pm (Pacific Time)"
---


## Course Description
Training on accessing Oceanographic Satellite Data from NOAA CoastWatch
and using the Animal Telemetry Network Portal.  This training was originally going to be held before
the annual AFS (American Fisheries Society) meeting in Honolulu, Hawaii, but has been rescheduled to be an [online course](https://meet.google.com/qip-azxk-jen), open to all.


## Instructors

 | Name              | Affiliation                    | 
 |:-----------------|:-----------------------------------------------------------------------------|
 | [Cara Wilson](mailto:cara.wilson@noaa.gov)       | CoastWatch/West Coast Node, PI |
 | [Dale Robinson](mailto:dale.robinson@noaa.gov)     | CoastWatch/West Coast Node, node manager |
 | [Megan McKinzie](mailto:mmckinzie@mbari.org)    | ATN Data Coordinator |
 | [Daisy Shi](mailto:hui.shi@noaa.gov)         | CoastWatch/Pacific OceanWatch, node manager |
    
## Objectives
* Describe the basic types of products available from satellite data
* Demonstate how to access data on ERDDAP servers 
* Explore the data available on the Animal Telemetry Network portal
* Introduce CoastWatch satellite data training resources
* Provide hands-on time to access data and try tutorials


## Schedule

| Time (PST)      | Topic                                                                         | Presenter                    |
|:-------------|:-----------------------------------------------------------------------------|:----------------------------|
| 10:00 - 10:15 | [Training  Overview - CoastWatch, ATN and the workshop component](../presentations/afs24/IntrotoCoastWatchandATNCourse.pptx.pdf)                   | [Cara Wilson](mailto:cara.wilson@noaa.gov)       | 
| 10:15 - 10:30 |  Group Introductions                                                              | [Cara Wilson](mailto:cara.wilson@noaa.gov)       |
| 10:30 - 11:15 | [Coastwatch satellite datasets and data portals](../presentations/afs24/Overview%20of%20Satellite%20Data%20.pptx.pdf)                                    | [Cara Wilson](mailto:cara.wilson@noaa.gov)       |
| 11:15 - 11:30 |   Break                                                                           |        |
| 11:30 - 12:00 | [Using the ERDDAP data server](../presentations/afs24/ERDDAP-intro.pptx.pdf)                                                      | [Cara Wilson](mailto:cara.wilson@noaa.gov)                 |
| 12:00 - 12:30 | [Accessing ERDDAP using scripts (R, python)](../presentations/afs24/GitHubTutorials.pptx.pdf)                                         | [Cara Wilson](mailto:cara.wilson@noaa.gov)       |
| 12:30 - 1:30  | Lunch break                                                                        |                   |  
| 1:30 - 2:00   | [Intro to ATN and the DAC](../presentations/afs24/McKinzie_Intro%20to%20ATN%20&%20the%20DAC_Satellite%20Data%20Training%20Course_25Oct24.pptx.pdf)                                                           | [Megan McKinzie](mailto:mmckinzie@mbari.org)    |
| 2:00 - 2:30   | Demo of ATN data portal                                                            | [Megan McKinzie](mailto:mmckinzie@mbari.org)    |
| 2:30 - 3:00   | [Accessing public ATN datasets](../presentations/afs24/McKinzie_Accessing%20Public%20ATN%20Data_25Oct24.pptx.pdf)                                                      | [Megan McKinzie](mailto:mmckinzie@mbari.org)    |
| 3:00 - 3:15   | Break                                                                              |                   |
| 3:15 - 3:30   | Workshop, part 1: Linking CoastWatch and ATN data using [scripts](https://github.com/madrichardson/coastwatch-training.github.io/tree/main/tutorials/matchup-satellite-data-to-ATN-animal-tracks)                    | [Daisy Shi](mailto:hui.shi@noaa.gov)       |
| 3:30 - 4:45   | Workshop, part 2: Hand’s on time                                                   |                   |
| 4:45 - 5:00   | Wrap up and final discussion                                                       | All               |


## Resources
- [Coastwatch Tutorials (on GitHub)](../../tutorials/index.qmd)
- [Coastwatch Lecture series](../../lectures/index.qmd)
- [Animal telemetry Network](https://portal.atn.ioos.us/)
