---
title: "2025 Long Island Sound Class"
description: "March 31-April 4, 2025"
---
Virtual - Times vary daily, see schedule below (times are Eastern).

NOAA CoastWatch is hosting this free, virtual training class: <br> **_Viewing and Analyzing Ocean/Coastal Events and Water Quality Using Satellites_**

[Join Class Via Zoom Here](https://ufl.zoom.us/j/95752530088?pwd=UX3hlHWv0ZBL6iExdl9gdApLWgaOVK.1)

## Course Description
Many satellite products are available for water quality applications and other uses from NOAA and other data providers. These include: chlorophyll, turbidity, sea surface temperature, organic matter, and more. 
In this course, learn how to use these satellite products for your region of interest using freely available tools. Address your needs and questions by creating maps and images, plotting a time series of varying conditions, or creating a virtual buoy for your study location. And other applications too!

This class is being offered in **_two Tiers_** as part of a larger Long Island Sound Project funded by New York/Connecticut Sea Grant. 


## Objectives

### Tier I: Creating Images
Learn to use tools to create images and maps of ocean or coastal features in your area of interest.
Tools taught: CoastWatch Data Portal, ArcGIS, ERDDAP visualization server, and more.

### Tier II: Analyzing Data for Your Study or Region 
Work more analytically with oceanographic satellite data. 
Learn R and/or Python techniques to access data on ERDDAP data servers for data extraction, map creation, time series analysis, matching data to your study site locations or ship tracks, creating a virtual buoy using satellite data in your location of choice, and other application skills.


## Schedule

| **Day**                   | **Time (ET)**       | **Topic**                                                                                                             | **Presenter**       |
|--------------------------|---------------------|-----------------------------------------------------------------------------------------------------------------------|---------------------|
| **Monday - March 31**    |                     | **Tier I and Tier II**                                                                                                |                     |
|                          | 9:00 - 9:15          | Presentation 1: [Overview – SeaGrant-funded Satellite Project](../presentations/longislandsound25/01-Course_Introduction.pdf)                                                          | Jonathan Sherman    |
|                          | 9:15 - 9:45          | Presentation 2: [Data Portal](../presentations/longislandsound25/02-Satellite_Training2024_CoastWatch_DataPortalOverView.pdf)                                                                                           | Michael Soracco     |
|                          | 9:45 - 10:15         | Presentation 3: [ArcGIS](../presentations/longislandsound25/03-ArcGIS_Training2021_General_DATA_r1.pdf)                                                                                                | Michael Soracco     |
|                          | 10:15 - 10:30        | Break                                                                                                                 |                     |
|                          | 10:30 - 11:15        | Presentation 4: [CoastWatch Utilities - CDAT](../presentations/longislandsound25/04-CoastWatch_Utilities_Intro_CDAT_LIS_2025-03.pdf) <br> [Files](../presentations/longislandsound25/exercise-materials/CDAT_Lesson_Files_Tier_1/)                                                                                                 | Ron Vogel           |
|                          | 11:15 - 11:30        | Q & A                                                                                                                 |                     |
|                          | 11:30 - 12:15        | Participant Exercise 1: Choose a tool and make a map <br> [ArcGIS files](../presentations/longislandsound25/exercise-materials/Exercise1_ArcGIS/), [CDAT files](../presentations/longislandsound25/exercise-materials/Exercise1_CDAT/) |                     |
|                          | 12:15 - 1:15         | **Lunch break**                                                                                                       |                     |
|                          | 1:15 - 1:45          | Presentation 5: [Choosing a Dataset](../presentations/longislandsound25/05-What_dataset_to_choose.pdf)                                                                                    | Jonathan Sherman    |
|                          | 1:45 - 2:45          | Presentation 6: [ERDDAP](../../tutorials/ERDDAP-Basics/)                                                                                                | Ron Vogel           |
|                          | 2:45 - 3:00          | Break                                                                                                                 |                     |
|                          | 3:00 - 3:30          | Q & A and Resources for Participants                                                                                  |                     |
|                          | 3:30 - 4:30          | Participant Exercise 2: Choose a dataset from ERDDAP, download, make a map and a time series <br> [Sample data list](../presentations/longislandsound25/exercise-materials/ERDDAP_Exercise_Instructions_Datasets.pdf)             |                     |
| **Tuesday - April 1**    |                     | **Tier II (April 1–4)**                                                                                               |                     |
|                          | 9:00 - 9:30          | Presentation 7: [Satellite 101](../presentations/longislandsound25/07-Satellite101_Part1_2025.pdf)                                                                                          | Shelly Tomlinson    |
|                          | 9:30 - 10:30         | Presentation 8: [CoastWatch Training Code (R and Python)](../presentations/longislandsound25/08-GitHubTutorials.pdf) – Capabilities and Tutorials <br> [Tutorials page](../../tutorials/index.qmd)                       | Jonathan Sherman    |
|                          | 10:30 - 10:45        | Break                                                                                                                 |                     |
|                          | 10:45 - 11:30        | Presentation 9: [CoastWatch Utilities - Command Line](../presentations/longislandsound25/09-CoastWatch_Utilities_Intro_CommandLine_LIS_2025-03.pdf) <br> [Files](../presentations/longislandsound25/exercise-materials/CDAT_Lesson_Files_Tier_2/)                 | Ron Vogel           |
|                          | 11:30 - 12:00        | Office Hours Logistics, Mini-project & Slide Info, Q & A                                                        |                     |
|                          | 12:00 - 1:00         | **Lunch**                                                                                                             |                     |
|                          | 1:00 - 4:00          | Office Hours: One-on-One                                                                                              |                     |
| **Wednesday - April 2**  |                     | Participants work on their mini-project on their own time                                                                  |                     |
| **Thursday - April 3**   | 9:00 - 9:15          | Gauge Progress Poll                                                                                                   | Betty Staugler      |
|                          | 9:15 - 9:30          | Presentation 10: [HAB Forecasts](../presentations/longislandsound25/10-Tomlinson_HABForecasting_LISoundApr12025.pdf)                                                                                        | Shelly Tomlinson    |
|                          | 9:30 - 9:45          | Presentation 11: [COVID Impacts](../presentations/longislandsound25/11-COVID_impacts.pdf)                                                            | Jonathan Sherman    |
|                          | 9:45 - 10:00         | Presentation 12: [Participant Slide Examples from Past Classes](../presentations/longislandsound25/12-Past_Participant_Slides_LIS_2025-03.pdf)                                                         | Ron Vogel    |
|                          | 10:00 - 12:00        | Office Hours: Group Discussion or One-on-One                                                                          |                     |
|                          | 12:00 - 1:00         | **Lunch**                                                                                                             |                     |
|                          | 1:00 - 4:00          | Participants work on their mini-project on their own time                                                                  |                     |
| **Friday - April 4**     | 1:00 - 3:00          | Final Mini-project Presentations (1 slide each)                                                                                   | Participants        |


## Resources
* [CoastWatch main website](https://coastwatch.noaa.gov/cwn/index.html)
* [CoastWatch East Coast Regional Node website](https://eastcoast.coastwatch.noaa.gov/)
* [CoastWatch Data Access methods](https://coastwatch.noaa.gov/cwn/data-access-tools.html)
* [Coastwatch Coding Tutorials: R and Python](../../tutorials/index.qmd)
* [Coastwatch Lecture series](../../lectures/index.qmd)
* [Coastwatch Data Portal video tutorials](https://umd.instructure.com/courses/1336575/pages/coastwatch-data-portal-tutorials)
* [Coastwatch ArcGIS lecture videos and tutorials](https://umd.instructure.com/courses/1336575/pages/arcgis-tutorials?module_item_id=12322036)
* CoastWatch Utilities
    * [CoastWatch Utilities Tutorials - CDAT and Command-Line](https://umd.instructure.com/courses/1336575/pages/coastwatch-utilities-tutorials)
    * [CDAT demo videos on YouTube](https://www.youtube.com/playlist?list=PL_-bsOLKMYJybI8chOl90HWWd_jTsaO3e)
* CoastWatch Help Desk
    * Email: coastwatch.info@noaa.gov
    * Phone: +1-301-683-3335
    * [User Forums](https://vlab.noaa.gov/web/coastwatch)


