---
title: "Access and Use Satellite Data and Decision-making tools for Ocean and Coastal Applications"
description: "November 26, 2024, In person, 1pm - 6pm (Fiji Standard Time)"
---


## Course Description
Training on accessing Oceanographic Satellite Data from NOAA CoastWatch and using information tools from PacIOOS for applications in the Pacific Islands region. This training will be held during the [2024 Pacific Islands GIS and Remote Sensing Users Conference](https://pgrsc.org) in Suva, Fiji.

Click here to [Register](https://lp.constantcontactpages.com/ev/reg/w28fcr4/lp/6d7fffe6-97b2-47fe-96e1-63f07a170611).

 
## Instructors

 | Name              | Affiliation                     | 
 |:-----------------|:-----------------------------------------------------------------------------|
 | [Daisy Shi](mailto:hui.shi@noaa.gov)         | CoastWatch/Pacific OceanWatch, node manager |
 | [Lauren Kaiser](mailto:lkaiser7@hawaii.edu)     | PacIOOS, data management specialist|
 | [Cara Wilson](mailto:cara.wilson@noaa.gov)       | CoastWatch/West Coast Node, PI |
  
## Objectives

* Describe the basic types of products available from satellite data
* Demonstrate how to access data on ERDDAP servers 
* Introduce CoastWatch satellite data and training resources
* Explore additional data and information tools available at PacIOOS
* Provide hands-on time to access data and run tutorials


## Schedule

| Time (Fiji Standard Time)   | Topic                                                                         | Presenter                    |
|:-------------|:-----------------------------------------------------------------------------|:----------------------------|
| 1:00 - 1:10 | [Welcome & Introductions](../presentations/pgrsc24/1-Intro_workshop.pptx.pdf)  | [Daisy Shi](mailto:hui.shi@noaa.gov) & [Lauren Kaiser](mailto:lkaiser7@hawaii.edu)  |
| 1:10 - 1:20 | Interactive Questions                                 |
| 1:20 - 1:35 | [Intro to CoastWatch, Satellite Datasets & Data Portal](../presentations/pgrsc24/2-Intro_CoastWatch.pptx.pdf)      | [Daisy Shi](mailto:hui.shi@noaa.gov)  |
| 1:35 - 1:50 | [Intro to OceanWatch, Data Accessibility & Usability](../presentations/pgrsc24/3-Intro-OceanWatch.pptx.pdf)      | [Daisy Shi](mailto:hui.shi@noaa.gov)  |
| 1:50 - 2:20 | [Intro to PacIOOS, Website Walkthrough & Data Search](../presentations/pgrsc24/4-About-PacIOOS_PIGISRS_Workshop.pdf)  | [Lauren Kaiser](mailto:lkaiser7@hawaii.edu) |
| 2:20 - 2:30 | Interactive Questions                                 |
| 2:30 - 2:45 |  Break                                                              | 
| 2:45 - 2:55 | [Overview of CoastWatch Tutorials](../presentations/pgrsc24/5-CoastWatch_tutorial.pptx.pdf)          |  [Daisy Shi](mailto:hui.shi@noaa.gov)  |
| 2:55 - 3:15 | [ERDDAP Demos](../presentations/pgrsc24/6-ERDDAP_Demo.pptx.pdf)                                | [Daisy Shi](mailto:hui.shi@noaa.gov)  |
| 3:15 - 3:45 | [ArcGIS & QGIS Demos](../presentations/pgrsc24/7-ArcGIS-Demo_PIGISRS_Workshop.pdf)                         | [Lauren Kaiser](mailto:lkaiser7@hawaii.edu) |
| 3:45 - 4:00 |   Break                                                                            |     
| 4:00 - 5:50 | [Hands-On time](https://drive.google.com/drive/folders/1zdvDnXf6QxAW3iCr9as1RUrp_CvfsmL3)              | All|
| 5:50 - 6:00 | Interactive Questions & Feedback                                |


## Resources
- [Coastwatch Tutorials (on GitHub)](https://github.com/coastwatch-training/CoastWatch-Tutorials/blob/main/README.md)
- [Coastwatch Lecture series](https://umd.instructure.com/courses/1336575/pages/all-lectures)
- [Geostationary satellites covering Western Pacific](https://umd.instructure.com/courses/1364405/pages/geostationary-satellites-covering-western-pacific)
- [PacIOOS](http://pacioos.org)
- [PacIOOS Voyager](http://pacioos.org/voyager)
