---
title: "2024 PolarWatch Sea Ice Training"
description: "October 21, 2024 Virtual 9am - 4pm (Pacific Time)"
---

PolarWatch node of the CoastWatch is hosting a free, virtual training class on [October 21, 2024 (9am-4pm Pacific Time)](https://meet.google.com/pjo-ajqf-qxn
). 


## Course Description
Many satellite sea ice products are available for download from NOAA and many other data providers: e.g. sea ice concentration, sea ice thickness, sea ice age, sea ice temperature, and sea ice extent. It can often be challenging to know the differences between the products and how each can be applied to a user's specific application. For example, the spatial resolutions of the products can vary widely, largely dependent on the type of satellite measurement the product is derived from (passive microwave, visible radiometry or synthetic aperture radar). Additionally, when working with data in the high-latitudes issues of data projection invariably arise and can complicate accessing and working with data. To address these issues, NOAA’s PolarWatch node has developed a 1-day (6 hour) online course with the following training objectives.

## Objectives
* Describe the basic types of sea-ice products available from satellite data
* Give an overview of working with different projections
* Explore the data available on the PolarWatch portal
* Provide hands-on time to access data and try tutorials
* Introduce CoastWatch and other sea ice satellite data training resources

## Schedule

| Time (PST)      | Topic                                                                     | Presenter                    |
|-------------|-----------------------------------------------------------------------------|----------------------------|
|9:00 - 9:30   |  [Presentation 1: Introduction to NOAA CoastWatch](../presentations/seaice24/IntrotoCoastWatchandSeaIceCourse.pptx.pdf)                          |  [Cara Wilson](mailto:cara.wilson@noaa.gov)           | 
|9:30 - 10:00  |  [Presentation 2: Overview of Sea Ice Remote Sensing](../presentations/seaice24/PolarWatch24_Presentation%202_Overview%20of%20Sea%20Ice%20Remote%20Sensing_Brucker.pdf)                                 | [Ludovic Brucker](mailto:ludovic.brucker@noaa.gov )       |
|10:00 - 10:30 |  [Presentation 3: JPSS Sea Ice Microlesson](../presentations/seaice24/JPSS_Microlesson_Training_Series_Sea_Ice_Products_KFuell_MSmith.pptx.pdf)                                 | [Kevin Fuell](mailto:kevin.fuell@nasa.gov )           |
|10:30 - 10:45 | Break                                                                      |                       |
|10:45 - 11:15 |  [Presentation 4: Sea Ice from SAR](../presentations/seaice24/CW_SeaIceSAR_Class_21Oct2024_CJackson_Final.pptx.pdf)                                         | [Chris Jackson](mailto:christopher.jackson@noaa.gov )         |
|11:15 - 11:30 |  [Presentation 5: Projections - Why they Matter](../presentations/seaice24/Satellite_Training2024_CoastWatch_IntroProjections.pdf)                            | [Michael Soracco](mailto:michael.soracco@noaa.gov)       |
|11:30 - 11:45 |  [Presentation 6: Ice in the Great Lakes](../presentations/seaice24/CW_Great_Lakes_Ice.pptx.pdf)                                   | [Andrea VanderWoude](mailto:andrea.vanderwoude@noaa.gov )    |
|11:45 - 12:45 | Lunch break                                                                |                       |  
|12:45 - 13:00 |  [Presentation 7: Projections in Action](../presentations/seaice24/Sea%20Ice%20Training%202024%20-%20Projection%20Calculations.pdf) ([Watch Video](https://www.youtube.com/watch?v=xUviYWCNE-c)) | [Peter Hollemans](mailto:peter@terrenus.ca)      |
|13:00 - 13:30 |  [Presentation 8: ERDDAP Demo](../presentations/seaice24/ERDDAP-intro-SeaIce.pptx.pdf)                                              | [Cara Wilson](mailto:cara.wilson@noaa.gov)            |
|13:30 - 13:45 |  [Presentation 9: PolarWatch Portal Demo](../presentations/seaice24/PolarWatch-Overview-PolarWatch-Portal-SHospital.pptx.pdf)                                  | [Sunny Hospital](mailto:sun.bak-hospital@noaa.gov)        |
|13:45 - 14:00 |  [Presentation 10: CoastWatch Viewer Demo](../presentations/seaice24/Satellite_Training2024_CoastWatch_DataPortalOverView.pdf)                                  | [Michael Soracco](mailto:michael.soracco@noaa.gov)       |
|14:00 - 14:15 | Break                                                                      |                       |                                    
|14:15 - 14:30 |  [Presentation 11: Overview of Tutorials](../presentations/seaice24/GitHubTutorials_PW.pptx.pdf)                                  |  [Cara Wilson](mailto:cara.wilson@noaa.gov), [Matthew Smith](mailto:matthew.r.smith@nasa.gov)          |
|14:30 - 16:00 |  Hand's on time, with instuctor's guidance available                       |                       |



## Resources
- [Coastwatch Tutorials](../../tutorials/index.qmd)
- [Coastwatch Lecture series](../../lectures/index.qmd)
- [JPSS Sea Ice Microlesson](https://weather.ndc.nasa.gov/sport/training-repo/#/JPSS-Sea-Ice-Microlesson)
