---
title: "Satellite 201 Summer Lecture Series"
description: "July 10, 17, 24 and 31, 2026, Virtual 11am - 1:30pm (Pacific Time)"
anchor-sections: false
---


## Course Description
This lecture series provides a deeper dive into satellite oceanography, exploring advanced topics beyond the regular CoastWatch satellite course.
[Link to registration page](https://forms.gle/XGtZWLqMAueXZQZX9)

## Schedule & Attendance
Frequency: Sessions are held every Friday for one month.  
Duration: Approximately 2.5 hours per session.   
Flexibility: Attendance for all sessions is not required; feel free to join the topics most relevant to you.

## 2026 Curriculum
The inaugural 2026 course will cover the following subjects:

* SAR Data: An introduction to Synthetic Aperture Radar.
* CoastWatch Utilities: An introduction to using the CoastWatch proprietary software suite.
* Beyond Chlorophyll: Exploring ocean color products other than chlorophyll. 
* Accessing CoastWatch Data: HTTPS and THREDDS Services.

## Meeting Privacy Notice

**To protect participant privacy, AI-powered meeting recording and transcription will not be used or allowed during this meeting. NOAA guidance requires participant consent when AI is used to collect, transcribe, or summarize personally identifiable information (PII). Because we cannot ensure consent from all participants, AI recording and transcription will not be permitted.**

For additional information on NOAA's privacy practices regarding AI-enabled meetings, see [NOAA's Privacy Statement](https://www.noaa.gov/protecting-your-privacy#:~:text=NOAA%20Privacy%20Statement).

## Schedule

<span class="text-bold-blue">Friday, July 10, 2026</span>

| Time (PST)      | Topic                                                                         | Presenter                    |
|:-------------|:-----------------------------------------------------------------------------|:----------------------------|
| 11:00 - 11:45   | [Introduction to SAR data](../presentations/sat201_26/CW_SAR_OverviewIntroduction_July2026_Final.pdf)                                     |  Chris Jackson  |
| 11:45 - 12:30   | [SAR Data Access](../presentations/sat201_26/CW_SAR_Access_vJUL2026.pdf)                                                      |     |
| 12:30 - 12:45   | Break                                                    |     |   
| 12:45 - 1:30   | Question & Answer and hand's on session                                                      |     | 


<span class="text-bold-blue">Friday, July 17, 2026</span>

| Time (PST)      | Topic                                                                         | Presenter                    |
|:-------------|:-----------------------------------------------------------------------------|:----------------------------|
| 11:00 - 11:45   | [Introduction to using Coastwatch Utilities software](../presentations/sat201_26/CoastWatch-Utilities-Satellite-201-2026.pdf)                                              |  Peter Hollemans   |
| 11:45 - 12:30   | A demo                                                     |     |
| 12:30 - 12:45   | Break                                                    |     |   
| 12:45 - 1:30   | Question & Answer and hand's on session                                                      |     | 


<span class="text-bold-blue">Friday, July 24, 2026</span>

| Time (PST)      | Topic                                                                         | Presenter                    |
|:-------------|:-----------------------------------------------------------------------------|:----------------------------|
| 11:00 - 11:45   | [Beyond Chlorophyll](../presentations/sat201_26/CoastWatch_Beyond_CHL_shorter.pdf)                                              |  Ryan Vandermeulen  |
| 11:45 - 12:30   | [Beyond Chlorophyll Case Study](../presentations/sat201_26/Case_study_and_resources_links.pdf)                              |     |
| 12:30 - 12:45   | Break                                                    |     |   
| 12:45 - 1:30   | Question & Answer and hand's on session                                                      |     | 

<span class="text-bold-blue">Friday, July 31, 2026</span>

| Time (PST)      | Topic                                                                         | Presenter                    |
|:-------------|:-----------------------------------------------------------------------------|:----------------------------|
| 11:00 - 11:45   | Accessing CoastWatch Data: HTTPS and THREDDS Services                                               | Madison Richardson & Dale Robinson   |
| 11:45 - 12:30   | [HTTPS](https://coastwatch-training.github.io/tutorials/codegallery.html#cg-access-data-from-https) & [THREDDS]((https://coastwatch-training.github.io/tutorials/codegallery.html#cg-access-data-from-thredds)) Demo                                                     |     |
| 12:30 - 12:45   | Break                                                    |     |   
| 12:45 - 1:30   | Question & Answer and hand's on session                                                      |     | 

## Instructors

 | Name              | Affiliation                    | 
 |:-----------------|:-----------------------------------------------------------------------------|
 | [Cara Wilson](mailto:cara.wilson@noaa.gov)       | CoastWatch/West Coast Node, PI |
 | [Dale Robinson](mailto:dale.robinson@noaa.gov)     | CoastWatch/West Coast Node, Development Lead |
 | [Madison Richardson](mailto:madison.richardson@noaa.gov)     | CoastWatch/West Coast Node, Environmental Data Analyst |
 | [Peter Hollemans](mailto:peter@terrenusearth.com)         | CoastWatch Utilities Developer |
 | [Ryan Vandermeulen](mailto:ryan.vandermeulen@noaa.gov)         | NOAA Fisheries Satellite Coordinator |
 | [Chris Jackson](mailto:christopher.jackson@noaa.gov)         | |

