<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Matchup satellite data to ship, glider, or animal tracks – CoastWatch Training</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../images/coastwatch.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-e1a5c8363afafaef2c763b6775fbf3ca.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-973137e60ee60a7e9cda953a542133da.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Matchup satellite data to ship, glider, or animal tracks</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../../../index.html" class="sidebar-logo-link">
      <img src="../../../images/coastwatch.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main">
    <a href="https://coastwatch.noaa.gov/cwn" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-globe"></i></a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../news-announcements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">News &amp; Announcements</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../trainings/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Training Classes</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Upcoming Trainings</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../trainings/upcoming/pgrsc26.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2026 PGRSC Course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../trainings/upcoming/sat201_26.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2026 Satellite 201 Summer Series</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Past Trainings</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../trainings/past/icft25.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2025 Satellite and Animal Telemetry</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../trainings/past/longislandsound25.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2025 Long Island Sound</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../trainings/past/pgrsc24.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2024 PGRSC Workshop</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../trainings/past/seaice24.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2024 Sea Ice Data Course</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../trainings/past/afs24.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2024 AFS Workshop</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../tutorials/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Training Tutorials</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../tutorials/codegallery.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Code Gallery</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Software Tutorials</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Software Information</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../tutorials/erddap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ERDDAP</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../tutorials/netcdf-panoply.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">NetCDF and Panoply</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../tutorials/cwutils.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">CoastWatch Utilities</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../tutorials/software.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Software Code Gallery</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../lectures/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course Lectures</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../officehours.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Office Hours</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About Us</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../help.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Help</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a>
  <ul class="collapse">
  <li><a href="#the-exercise-demonstrates-the-following-techniques" id="toc-the-exercise-demonstrates-the-following-techniques" class="nav-link" data-scroll-target="#the-exercise-demonstrates-the-following-techniques">The exercise demonstrates the following techniques:</a></li>
  <li><a href="#datasets-used" id="toc-datasets-used" class="nav-link" data-scroll-target="#datasets-used">Datasets used:</a></li>
  <li><a href="#python-packages-used" id="toc-python-packages-used" class="nav-link" data-scroll-target="#python-packages-used">Python packages used:</a></li>
  </ul></li>
  <li><a href="#import-the-required-python-modules" id="toc-import-the-required-python-modules" class="nav-link" data-scroll-target="#import-the-required-python-modules">Import the required Python modules</a></li>
  <li><a href="#load-the-track-data-into-a-pandas-data-frame" id="toc-load-the-track-data-into-a-pandas-data-frame" class="nav-link" data-scroll-target="#load-the-track-data-into-a-pandas-data-frame">Load the track data into a Pandas data frame</a></li>
  <li><a href="#plot-the-track-on-a-map" id="toc-plot-the-track-on-a-map" class="nav-link" data-scroll-target="#plot-the-track-on-a-map">Plot the track on a map</a></li>
  <li><a href="#prepare-track-data-for-use-to-extract-satellite-data" id="toc-prepare-track-data-for-use-to-extract-satellite-data" class="nav-link" data-scroll-target="#prepare-track-data-for-use-to-extract-satellite-data">Prepare track data for use to extract satellite data</a>
  <ul class="collapse">
  <li><a href="#create-a-column-with-pandas-date-objects" id="toc-create-a-column-with-pandas-date-objects" class="nav-link" data-scroll-target="#create-a-column-with-pandas-date-objects">Create a column with Pandas date objects</a></li>
  </ul></li>
  <li><a href="#extract-data-from-a-satellite-dataset-corresponding-to-points-on-the-track" id="toc-extract-data-from-a-satellite-dataset-corresponding-to-points-on-the-track" class="nav-link" data-scroll-target="#extract-data-from-a-satellite-dataset-corresponding-to-points-on-the-track">Extract data from a satellite dataset corresponding to points on the track</a>
  <ul class="collapse">
  <li><a href="#select-a-dataset" id="toc-select-a-dataset" class="nav-link" data-scroll-target="#select-a-dataset">Select a dataset</a></li>
  <li><a href="#open-the-satellite-data-in-xarray" id="toc-open-the-satellite-data-in-xarray" class="nav-link" data-scroll-target="#open-the-satellite-data-in-xarray">Open the satellite data in Xarray</a></li>
  <li><a href="#download-the-satellite-data-that-corresponds-to-each-track-location" id="toc-download-the-satellite-data-that-corresponds-to-each-track-location" class="nav-link" data-scroll-target="#download-the-satellite-data-that-corresponds-to-each-track-location">Download the satellite data that corresponds to each track location</a></li>
  <li><a href="#consolidate-the-downloaded-satellite-data-into-the-track-data-frame" id="toc-consolidate-the-downloaded-satellite-data-into-the-track-data-frame" class="nav-link" data-scroll-target="#consolidate-the-downloaded-satellite-data-into-the-track-data-frame">Consolidate the downloaded satellite data into the track data frame</a></li>
  <li><a href="#save-your-work" id="toc-save-your-work" class="nav-link" data-scroll-target="#save-your-work">Save your work</a></li>
  </ul></li>
  <li><a href="#plot-chlorophyll-matchup-data-onto-a-map" id="toc-plot-chlorophyll-matchup-data-onto-a-map" class="nav-link" data-scroll-target="#plot-chlorophyll-matchup-data-onto-a-map">Plot chlorophyll matchup data onto a map</a>
  <ul class="collapse">
  <li><a href="#first-plot-a-histogram-of-the-chlorophyll-data" id="toc-first-plot-a-histogram-of-the-chlorophyll-data" class="nav-link" data-scroll-target="#first-plot-a-histogram-of-the-chlorophyll-data">First plot a histogram of the chlorophyll data</a></li>
  <li><a href="#plot-a-histogram-of-the-log-of-the-chlorophyll-data" id="toc-plot-a-histogram-of-the-log-of-the-chlorophyll-data" class="nav-link" data-scroll-target="#plot-a-histogram-of-the-log-of-the-chlorophyll-data">Plot a histogram of the log of the chlorophyll data</a></li>
  <li><a href="#map-the-chlorophyll-data" id="toc-map-the-chlorophyll-data" class="nav-link" data-scroll-target="#map-the-chlorophyll-data">Map the chlorophyll data</a></li>
  </ul></li>
  <li><a href="#on-your-own" id="toc-on-your-own" class="nav-link" data-scroll-target="#on-your-own">On your own!</a></li>
  <li><a href="#match-satellite-chlorophyll-to-dusky-shark-telemetry" id="toc-match-satellite-chlorophyll-to-dusky-shark-telemetry" class="nav-link" data-scroll-target="#match-satellite-chlorophyll-to-dusky-shark-telemetry">Match satellite chlorophyll to Dusky shark telemetry</a>
  <ul class="collapse">
  <li><a href="#load-dusky-shark-telemetry-data" id="toc-load-dusky-shark-telemetry-data" class="nav-link" data-scroll-target="#load-dusky-shark-telemetry-data">Load Dusky shark telemetry data</a></li>
  <li><a href="#convert-telemetry-columns-to-coordinate-arrays" id="toc-convert-telemetry-columns-to-coordinate-arrays" class="nav-link" data-scroll-target="#convert-telemetry-columns-to-coordinate-arrays">Convert telemetry columns to coordinate arrays</a></li>
  <li><a href="#open-a-satellite-dataset-using-xarray-opendap" id="toc-open-a-satellite-dataset-using-xarray-opendap" class="nav-link" data-scroll-target="#open-a-satellite-dataset-using-xarray-opendap">Open a satellite dataset using Xarray (OPeNDAP)</a></li>
  <li><a href="#match-each-shark-detection-to-a-local-satellite-window-0.2" id="toc-match-each-shark-detection-to-a-local-satellite-window-0.2" class="nav-link" data-scroll-target="#match-each-shark-detection-to-a-local-satellite-window-0.2">Match each shark detection to a local satellite window (±0.2°)</a></li>
  <li><a href="#run-the-matchup-for-all-shark-detections" id="toc-run-the-matchup-for-all-shark-detections" class="nav-link" data-scroll-target="#run-the-matchup-for-all-shark-detections">Run the matchup for all shark detections</a></li>
  <li><a href="#assemble-a-consolidated-telemetrysatellite-dataset" id="toc-assemble-a-consolidated-telemetrysatellite-dataset" class="nav-link" data-scroll-target="#assemble-a-consolidated-telemetrysatellite-dataset">Assemble a consolidated telemetry–satellite dataset</a></li>
  <li><a href="#map-of-all-sharks-colored-by-chlorophyll" id="toc-map-of-all-sharks-colored-by-chlorophyll" class="nav-link" data-scroll-target="#map-of-all-sharks-colored-by-chlorophyll">Map of all sharks colored by chlorophyll</a></li>
  <li><a href="#subset-all-tags-for-a-single-shark" id="toc-subset-all-tags-for-a-single-shark" class="nav-link" data-scroll-target="#subset-all-tags-for-a-single-shark">Subset all tags for a single shark</a></li>
  <li><a href="#plot-the-movement-track-for-a-single-shark" id="toc-plot-the-movement-track-for-a-single-shark" class="nav-link" data-scroll-target="#plot-the-movement-track-for-a-single-shark">Plot the movement track for a single shark</a></li>
  <li><a href="#compare-chlorophyll-conditions-by-year-using-a-boxplot" id="toc-compare-chlorophyll-conditions-by-year-using-a-boxplot" class="nav-link" data-scroll-target="#compare-chlorophyll-conditions-by-year-using-a-boxplot">Compare chlorophyll conditions by year using a boxplot</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Matchup satellite data to ship, glider, or animal tracks</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<blockquote class="blockquote">
<p>History | Updated Feb 2026</p>
</blockquote>
<p>In this exercise you will extract satellite data around a set of points defined by longitude, latitude, and time coordinates, like that produced by an animal telemetry tag, and ship track, or a glider tract.</p>
<p>Please note that there may be more efficient ways, more Pythonic ways, to accomplish the tasks in this tutorial. The tutorial was developed to be easier to follow for less experienced users of Python.</p>
<section id="the-exercise-demonstrates-the-following-techniques" class="level3">
<h3 class="anchored" data-anchor-id="the-exercise-demonstrates-the-following-techniques">The exercise demonstrates the following techniques:</h3>
<ul>
<li>Loading data from a tab- or comma-separated file</li>
<li>Plotting the latitude/longitude points onto a map</li>
<li>Extracting satellite data along a track</li>
<li>Summarizing satellite values using either a single nearest pixel or a small spatial window</li>
<li>Saving results as a CSV file</li>
<li>Plotting the satellite data onto a map</li>
</ul>
</section>
<section id="datasets-used" class="level3">
<h3 class="anchored" data-anchor-id="datasets-used">Datasets used:</h3>
<ul>
<li>Chlorophyll a concentration from the European Space Agency’s Ocean Colour Climate Change Initiative Monthly dataset v6.0</li>
<li>A loggerhead turtle telemetry track that has been subsample to reduce the data requests needed for this tutorial from over 1200 to 25. The turtle was raised in captivity in Japan, then tagged and released on 05/04/2005 in the Central Pacific. Its tag transmitted for over 3 years and went all the way to the Southern tip of Baja California. The track data can be downloaded from <code>data</code> folder in this project folder.</li>
<li>Dusky shark telemetry detections, consisting of longitude, latitude, date, and transmitter ID information from acoustic tags deployed along the U.S. East Coast. This example demonstrates matching satellite chlorophyll using a small spatial window (±0.2°) to better represent local environmental conditions experienced by the animal.</li>
<li>Chlorophyll-a, Aqua MODIS, NPP, L3SMI, Global, 4km, Science Quality, 2003-present (8 Day Composite)</li>
</ul>
</section>
<section id="python-packages-used" class="level3">
<h3 class="anchored" data-anchor-id="python-packages-used">Python packages used:</h3>
<ul>
<li>pandas (reading and analyzing data)<br>
</li>
<li>numpy (data analysis, manipulation)</li>
<li>xarray (multi-dimensional data analysis, manipulation)</li>
<li>matplotlib (mapping)</li>
<li>cartopy (mapping)</li>
<li>datetime (date manipulation)</li>
</ul>
</section>
</section>
<section id="import-the-required-python-modules" class="level2">
<h2 class="anchored" data-anchor-id="import-the-required-python-modules">Import the required Python modules</h2>
<div id="cell-3" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> clear_output</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cartopy.crs <span class="im">as</span> ccrs</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cartopy.feature <span class="im">as</span> cfeature</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> cartopy.mpl.ticker <span class="im">import</span> LongitudeFormatter, LatitudeFormatter</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> cartopy.mpl.gridliner <span class="im">import</span> LONGITUDE_FORMATTER, LATITUDE_FORMATTER</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> xarray <span class="im">as</span> xr</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-the-track-data-into-a-pandas-data-frame" class="level2">
<h2 class="anchored" data-anchor-id="load-the-track-data-into-a-pandas-data-frame">Load the track data into a Pandas data frame</h2>
<p>Below, the track data will load using the Pandas “read_csv” method. * Then use the “.head()” method to view the column names and the first few rows of data.</p>
<div id="cell-5" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>track_path <span class="op">=</span> os.path.join(<span class="st">'..'</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                          <span class="st">'data'</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                          <span class="st">'25317_05_subsampled.dat'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(track_path)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.head(<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     mean_lon   mean_lat  year  month  day
0  176.619433  32.678728  2005      5    4
1  175.860895  35.057734  2005      6   23</code></pre>
</div>
</div>
</section>
<section id="plot-the-track-on-a-map" class="level2">
<h2 class="anchored" data-anchor-id="plot-the-track-on-a-map">Plot the track on a map</h2>
<div id="cell-7" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">10</span>))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Label axes of a Plate Carree projection with a central longitude of 180:</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>ax1 <span class="op">=</span> plt.subplot(<span class="dv">211</span>, projection<span class="op">=</span>ccrs.PlateCarree(central_longitude<span class="op">=</span><span class="dv">180</span>))</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the lon and lat ranges to set the extent of the map</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># the 120, 260 lon range will show the whole Pacific</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># the 15, 55 lat range with capture the range of the data</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>ax1.set_extent([<span class="dv">120</span>, <span class="dv">260</span>, <span class="dv">15</span>, <span class="dv">55</span>], ccrs.PlateCarree())</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the tick marks to be slightly inside the map extents</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>ax1.set_xticks(<span class="bu">range</span>(<span class="dv">125</span>, <span class="dv">255</span>, <span class="dv">20</span>), crs<span class="op">=</span>ccrs.PlateCarree())</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>ax1.set_yticks(<span class="bu">range</span>(<span class="dv">20</span>, <span class="dv">60</span>, <span class="dv">10</span>), crs<span class="op">=</span>ccrs.PlateCarree())</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Add feature to the map</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>ax1.add_feature(cfeature.LAND, facecolor<span class="op">=</span><span class="st">'0.6'</span>)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>ax1.coastlines()</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Format the lat and lon axis labels</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>lon_formatter <span class="op">=</span> LongitudeFormatter(zero_direction_label<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>lat_formatter <span class="op">=</span> LatitudeFormatter()</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>ax1.xaxis.set_major_formatter(lon_formatter)</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>ax1.yaxis.set_major_formatter(lat_formatter)</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Bring the lon and lat data into a numpy array </span></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>x, y <span class="op">=</span> df.mean_lon.to_numpy(), df.mean_lat.to_numpy()</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>ax1 <span class="op">=</span> plt.plot(x, y, transform<span class="op">=</span>ccrs.PlateCarree(), color<span class="op">=</span><span class="st">'k'</span>)</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a><span class="co"># start point in green star</span></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>ax1 <span class="op">=</span> plt.plot(x[<span class="dv">0</span>], y[<span class="dv">0</span>],</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>               marker<span class="op">=</span><span class="st">'*'</span>,</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>               color<span class="op">=</span><span class="st">'g'</span>,</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>               transform<span class="op">=</span>ccrs.PlateCarree(),</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>               markersize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a><span class="co"># end point in red X</span></span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>ax1 <span class="op">=</span> plt.plot(x[<span class="op">-</span><span class="dv">1</span>], y[<span class="op">-</span><span class="dv">1</span>],</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>               marker<span class="op">=</span><span class="st">'X'</span>,</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>               color<span class="op">=</span><span class="st">'r'</span>,</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>               transform<span class="op">=</span>ccrs.PlateCarree(),</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>               markersize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Animal Track for Turtle #25317'</span>, fontsize<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="satellite_matchups_to_track_locations_xarray_files/figure-html/cell-4-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="prepare-track-data-for-use-to-extract-satellite-data" class="level2">
<h2 class="anchored" data-anchor-id="prepare-track-data-for-use-to-extract-satellite-data">Prepare track data for use to extract satellite data</h2>
<section id="create-a-column-with-pandas-date-objects" class="level3">
<h3 class="anchored" data-anchor-id="create-a-column-with-pandas-date-objects">Create a column with Pandas date objects</h3>
<p><strong>Reload the “25317_05_subsampled.dat”. This time we will use the “parse_dates” option to create a Pandas date object column (year_month_day) from the ‘year’, ‘month’, and ‘day’ columns.</strong></p>
<div id="cell-9" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(track_path,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                 parse_dates<span class="op">=</span>[[<span class="st">'year'</span>, <span class="st">'month'</span>, <span class="st">'day'</span>]]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                 )</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'The new year_month_day column contains the Pandas date objects'</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.head(<span class="dv">2</span>))</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.dtypes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The new year_month_day column contains the Pandas date objects
  year_month_day    mean_lon   mean_lat
0     2005-05-04  176.619433  32.678728
1     2005-06-23  175.860895  35.057734
year_month_day    datetime64[ns]
mean_lon                 float64
mean_lat                 float64
dtype: object</code></pre>
</div>
</div>
</section>
</section>
<section id="extract-data-from-a-satellite-dataset-corresponding-to-points-on-the-track" class="level2">
<h2 class="anchored" data-anchor-id="extract-data-from-a-satellite-dataset-corresponding-to-points-on-the-track">Extract data from a satellite dataset corresponding to points on the track</h2>
<p>We are going to download data from an ERDDAP server using the following steps: * Select a dataset on an ERDDAP server * Open the dataset using the Xarray module * Loop though the track data and pull out the date, latitude and longitude coordinates from each row * Insert these coordinates into the Xarray open-dataset object to select and download the satellite data that corresponds to the coordinates. * Store the satellite data in a temporary Pandas data frame * Once all the satellite data has been added to the temporary data frame, merge it with the track data frame.</p>
<section id="select-a-dataset" class="level3">
<h3 class="anchored" data-anchor-id="select-a-dataset">Select a dataset</h3>
<p>We’ll use the European Space Agency’s OC-CCI product (https://climate.esa.int/en/projects/ocean-colour/) to obtain chlorophyll data. This is a merged product that blends data from many ocean color sensors to create a long time series (1997-present) with better spatial coverage than any single sensor.</p>
<p>Ideally we would use a daily dataset, selecting the day that corresponds to the track data date. However, chlorophyll measurements can have a lot of missing data, primarily due to cloud cover. To reduce data gaps and improve the likelihood of data for our matchups, we can use a dataset that combines all of the data from each month into the monthly average.</p>
<p><strong>The ERDDAP URL to the monthly version of the OC-CCI product is below:</strong><br>
https://oceanwatch.pifsc.noaa.gov/erddap/griddap/esa-cci-chla-monthly-v6-0</p>
</section>
<section id="open-the-satellite-data-in-xarray" class="level3">
<h3 class="anchored" data-anchor-id="open-the-satellite-data-in-xarray">Open the satellite data in Xarray</h3>
<ul>
<li>Use the ERDDAP URL with no extension (e.g.&nbsp;without .html or .graph…). This is the OPeNDAP URL, which allows viewing the dataset metadata and, when you select the data you want, downloading the data.</li>
<li>Use the Xarray “open_dataset” function then view the metadata</li>
</ul>
<div id="cell-12" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>erddap_url <span class="op">=</span> <span class="st">'/'</span>.join([<span class="st">'https://oceanwatch.pifsc.noaa.gov'</span>,</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>                       <span class="st">'erddap'</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                       <span class="st">'griddap'</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                       <span class="st">'esa-cci-chla-monthly-v6-0'</span>])</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>ds <span class="op">=</span> xr.open_dataset(erddap_url)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>ds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div><svg style="position: absolute; width: 0; height: 0; overflow: hidden">
<defs>
<symbol id="icon-database" viewbox="0 0 32 32">
<path d="M16 0c-8.837 0-16 2.239-16 5v4c0 2.761 7.163 5 16 5s16-2.239 16-5v-4c0-2.761-7.163-5-16-5z"></path>
<path d="M16 17c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
<path d="M16 26c-8.837 0-16-2.239-16-5v6c0 2.761 7.163 5 16 5s16-2.239 16-5v-6c0 2.761-7.163 5-16 5z"></path>
</symbol>
<symbol id="icon-file-text2" viewbox="0 0 32 32">
<path d="M28.681 7.159c-0.694-0.947-1.662-2.053-2.724-3.116s-2.169-2.030-3.116-2.724c-1.612-1.182-2.393-1.319-2.841-1.319h-15.5c-1.378 0-2.5 1.121-2.5 2.5v27c0 1.378 1.122 2.5 2.5 2.5h23c1.378 0 2.5-1.122 2.5-2.5v-19.5c0-0.448-0.137-1.23-1.319-2.841zM24.543 5.457c0.959 0.959 1.712 1.825 2.268 2.543h-4.811v-4.811c0.718 0.556 1.584 1.309 2.543 2.268zM28 29.5c0 0.271-0.229 0.5-0.5 0.5h-23c-0.271 0-0.5-0.229-0.5-0.5v-27c0-0.271 0.229-0.5 0.5-0.5 0 0 15.499-0 15.5 0v7c0 0.552 0.448 1 1 1h7v19.5z"></path>
<path d="M23 26h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 22h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
<path d="M23 18h-14c-0.552 0-1-0.448-1-1s0.448-1 1-1h14c0.552 0 1 0.448 1 1s-0.448 1-1 1z"></path>
</symbol>
</defs>
</svg>
<style>/* CSS stylesheet for displaying xarray objects in jupyterlab.
 *
 */

:root {
  --xr-font-color0: var(--jp-content-font-color0, rgba(0, 0, 0, 1));
  --xr-font-color2: var(--jp-content-font-color2, rgba(0, 0, 0, 0.54));
  --xr-font-color3: var(--jp-content-font-color3, rgba(0, 0, 0, 0.38));
  --xr-border-color: var(--jp-border-color2, #e0e0e0);
  --xr-disabled-color: var(--jp-layout-color3, #bdbdbd);
  --xr-background-color: var(--jp-layout-color0, white);
  --xr-background-color-row-even: var(--jp-layout-color1, white);
  --xr-background-color-row-odd: var(--jp-layout-color2, #eeeeee);
}

html[theme=dark],
body[data-theme=dark],
body.vscode-dark {
  --xr-font-color0: rgba(255, 255, 255, 1);
  --xr-font-color2: rgba(255, 255, 255, 0.54);
  --xr-font-color3: rgba(255, 255, 255, 0.38);
  --xr-border-color: #1F1F1F;
  --xr-disabled-color: #515151;
  --xr-background-color: #111111;
  --xr-background-color-row-even: #111111;
  --xr-background-color-row-odd: #313131;
}

.xr-wrap {
  display: block !important;
  min-width: 300px;
  max-width: 700px;
}

.xr-text-repr-fallback {
  /* fallback to plain text repr when CSS is not injected (untrusted notebook) */
  display: none;
}

.xr-header {
  padding-top: 6px;
  padding-bottom: 6px;
  margin-bottom: 4px;
  border-bottom: solid 1px var(--xr-border-color);
}

.xr-header > div,
.xr-header > ul {
  display: inline;
  margin-top: 0;
  margin-bottom: 0;
}

.xr-obj-type,
.xr-array-name {
  margin-left: 2px;
  margin-right: 10px;
}

.xr-obj-type {
  color: var(--xr-font-color2);
}

.xr-sections {
  padding-left: 0 !important;
  display: grid;
  grid-template-columns: 150px auto auto 1fr 20px 20px;
}

.xr-section-item {
  display: contents;
}

.xr-section-item input {
  display: none;
}

.xr-section-item input + label {
  color: var(--xr-disabled-color);
}

.xr-section-item input:enabled + label {
  cursor: pointer;
  color: var(--xr-font-color2);
}

.xr-section-item input:enabled + label:hover {
  color: var(--xr-font-color0);
}

.xr-section-summary {
  grid-column: 1;
  color: var(--xr-font-color2);
  font-weight: 500;
}

.xr-section-summary > span {
  display: inline-block;
  padding-left: 0.5em;
}

.xr-section-summary-in:disabled + label {
  color: var(--xr-font-color2);
}

.xr-section-summary-in + label:before {
  display: inline-block;
  content: '►';
  font-size: 11px;
  width: 15px;
  text-align: center;
}

.xr-section-summary-in:disabled + label:before {
  color: var(--xr-disabled-color);
}

.xr-section-summary-in:checked + label:before {
  content: '▼';
}

.xr-section-summary-in:checked + label > span {
  display: none;
}

.xr-section-summary,
.xr-section-inline-details {
  padding-top: 4px;
  padding-bottom: 4px;
}

.xr-section-inline-details {
  grid-column: 2 / -1;
}

.xr-section-details {
  display: none;
  grid-column: 1 / -1;
  margin-bottom: 5px;
}

.xr-section-summary-in:checked ~ .xr-section-details {
  display: contents;
}

.xr-array-wrap {
  grid-column: 1 / -1;
  display: grid;
  grid-template-columns: 20px auto;
}

.xr-array-wrap > label {
  grid-column: 1;
  vertical-align: top;
}

.xr-preview {
  color: var(--xr-font-color3);
}

.xr-array-preview,
.xr-array-data {
  padding: 0 5px !important;
  grid-column: 2;
}

.xr-array-data,
.xr-array-in:checked ~ .xr-array-preview {
  display: none;
}

.xr-array-in:checked ~ .xr-array-data,
.xr-array-preview {
  display: inline-block;
}

.xr-dim-list {
  display: inline-block !important;
  list-style: none;
  padding: 0 !important;
  margin: 0;
}

.xr-dim-list li {
  display: inline-block;
  padding: 0;
  margin: 0;
}

.xr-dim-list:before {
  content: '(';
}

.xr-dim-list:after {
  content: ')';
}

.xr-dim-list li:not(:last-child):after {
  content: ',';
  padding-right: 5px;
}

.xr-has-index {
  font-weight: bold;
}

.xr-var-list,
.xr-var-item {
  display: contents;
}

.xr-var-item > div,
.xr-var-item label,
.xr-var-item > .xr-var-name span {
  background-color: var(--xr-background-color-row-even);
  margin-bottom: 0;
}

.xr-var-item > .xr-var-name:hover span {
  padding-right: 5px;
}

.xr-var-list > li:nth-child(odd) > div,
.xr-var-list > li:nth-child(odd) > label,
.xr-var-list > li:nth-child(odd) > .xr-var-name span {
  background-color: var(--xr-background-color-row-odd);
}

.xr-var-name {
  grid-column: 1;
}

.xr-var-dims {
  grid-column: 2;
}

.xr-var-dtype {
  grid-column: 3;
  text-align: right;
  color: var(--xr-font-color2);
}

.xr-var-preview {
  grid-column: 4;
}

.xr-index-preview {
  grid-column: 2 / 5;
  color: var(--xr-font-color2);
}

.xr-var-name,
.xr-var-dims,
.xr-var-dtype,
.xr-preview,
.xr-attrs dt {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  padding-right: 10px;
}

.xr-var-name:hover,
.xr-var-dims:hover,
.xr-var-dtype:hover,
.xr-attrs dt:hover {
  overflow: visible;
  width: auto;
  z-index: 1;
}

.xr-var-attrs,
.xr-var-data,
.xr-index-data {
  display: none;
  background-color: var(--xr-background-color) !important;
  padding-bottom: 5px !important;
}

.xr-var-attrs-in:checked ~ .xr-var-attrs,
.xr-var-data-in:checked ~ .xr-var-data,
.xr-index-data-in:checked ~ .xr-index-data {
  display: block;
}

.xr-var-data > table {
  float: right;
}

.xr-var-name span,
.xr-var-data,
.xr-index-name div,
.xr-index-data,
.xr-attrs {
  padding-left: 25px !important;
}

.xr-attrs,
.xr-var-attrs,
.xr-var-data,
.xr-index-data {
  grid-column: 1 / -1;
}

dl.xr-attrs {
  padding: 0;
  margin: 0;
  display: grid;
  grid-template-columns: 125px auto;
}

.xr-attrs dt,
.xr-attrs dd {
  padding: 0;
  margin: 0;
  float: left;
  padding-right: 10px;
  width: auto;
}

.xr-attrs dt {
  font-weight: normal;
  grid-column: 1;
}

.xr-attrs dt:hover span {
  display: inline-block;
  background: var(--xr-background-color);
  padding-right: 10px;
}

.xr-attrs dd {
  grid-column: 2;
  white-space: pre-wrap;
  word-break: break-all;
}

.xr-icon-database,
.xr-icon-file-text2,
.xr-no-icon {
  display: inline-block;
  vertical-align: middle;
  width: 1em;
  height: 1.5em !important;
  stroke-width: 0;
  stroke: currentColor;
  fill: currentColor;
}
</style><pre class="xr-text-repr-fallback">&lt;xarray.Dataset&gt; Size: 472GB
Dimensions:             (time: 316, latitude: 4320, longitude: 8640)
Coordinates:
  * time                (time) datetime64[ns] 3kB 1997-09-04 ... 2023-12-01
  * latitude            (latitude) float64 35kB 89.98 89.94 ... -89.94 -89.98
  * longitude           (longitude) float64 69kB 0.02083 0.0625 ... 359.9 360.0
Data variables:
    chlor_a             (time, latitude, longitude) float32 47GB ...
    MERIS_nobs_sum      (time, latitude, longitude) float32 47GB ...
    MODISA_nobs_sum     (time, latitude, longitude) float32 47GB ...
    OLCI_A_nobs_sum     (time, latitude, longitude) float32 47GB ...
    OLCI_B_nobs_sum     (time, latitude, longitude) float32 47GB ...
    SeaWiFS_nobs_sum    (time, latitude, longitude) float32 47GB ...
    VIIRS_nobs_sum      (time, latitude, longitude) float32 47GB ...
    chlor_a_log10_bias  (time, latitude, longitude) float32 47GB ...
    chlor_a_log10_rmsd  (time, latitude, longitude) float32 47GB ...
    total_nobs_sum      (time, latitude, longitude) float32 47GB ...
Attributes: (12/53)
    cdm_data_type:                     Grid
    comment:                           See summary attribute
    Conventions:                       CF-1.7, COARDS, ACDD-1.3
    creation_date:                     Thu Jan 18 09:04:18 2024
    creator_email:                     help@esa-oceancolour-cci.org
    creator_name:                      Plymouth Marine Laboratory
    ...                                ...
    time_coverage_end:                 2023-12-01T00:00:00Z
    time_coverage_resolution:          P1M
    time_coverage_start:               1997-09-04T00:00:00Z
    title:                             Chlorophyll a concentration, ESA OC CC...
    tracking_id:                       abd52a4c-7009-464f-b1eb-958f7d333a1d
    Westernmost_Easting:               0.020833333333314386</pre><div class="xr-wrap" style="display:none"><div class="xr-header"><div class="xr-obj-type">xarray.Dataset</div></div><ul class="xr-sections"><li class="xr-section-item"><input id="section-4c654eb2-5c0b-4dfb-a82c-d22a5ccf2241" class="xr-section-summary-in" type="checkbox" disabled=""><label for="section-4c654eb2-5c0b-4dfb-a82c-d22a5ccf2241" class="xr-section-summary" title="Expand/collapse section">Dimensions:</label><div class="xr-section-inline-details"><ul class="xr-dim-list"><li><span class="xr-has-index">time</span>: 316</li><li><span class="xr-has-index">latitude</span>: 4320</li><li><span class="xr-has-index">longitude</span>: 8640</li></ul></div><div class="xr-section-details"></div></li><li class="xr-section-item"><input id="section-547359ff-9ec3-4b10-86e3-cfd60ca79052" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-547359ff-9ec3-4b10-86e3-cfd60ca79052" class="xr-section-summary">Coordinates: <span>(3)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span class="xr-has-index">time</span></div><div class="xr-var-dims">(time)</div><div class="xr-var-dtype">datetime64[ns]</div><div class="xr-var-preview xr-preview">1997-09-04 ... 2023-12-01</div><input id="attrs-586c6c78-3bd5-4cfe-a424-8987862ac555" class="xr-var-attrs-in" type="checkbox"><label for="attrs-586c6c78-3bd5-4cfe-a424-8987862ac555" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-c149f1d1-dcde-4091-b936-16f3b743e18c" class="xr-var-data-in" type="checkbox"><label for="data-c149f1d1-dcde-4091-b936-16f3b743e18c" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>_CoordinateAxisType :</span></dt><dd>Time</dd><dt><span>actual_range :</span></dt><dd>[8.7333120e+08 1.7013888e+09]</dd><dt><span>axis :</span></dt><dd>T</dd><dt><span>ioos_category :</span></dt><dd>Time</dd><dt><span>long_name :</span></dt><dd>Time</dd><dt><span>standard_name :</span></dt><dd>time</dd><dt><span>time_origin :</span></dt><dd>01-JAN-1970 00:00:00</dd></dl></div><div class="xr-var-data"><pre>array(['1997-09-04T00:00:00.000000000', '1997-10-01T00:00:00.000000000',
       '1997-11-01T00:00:00.000000000', ..., '2023-10-01T00:00:00.000000000',
       '2023-11-01T00:00:00.000000000', '2023-12-01T00:00:00.000000000'],
      dtype='datetime64[ns]')</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span class="xr-has-index">latitude</span></div><div class="xr-var-dims">(latitude)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">89.98 89.94 89.9 ... -89.94 -89.98</div><input id="attrs-b2019ce0-120e-4861-aca3-d084008d1a44" class="xr-var-attrs-in" type="checkbox"><label for="attrs-b2019ce0-120e-4861-aca3-d084008d1a44" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-5491164c-9cdd-4e05-b7b2-fec8ea7a4b3b" class="xr-var-data-in" type="checkbox"><label for="data-5491164c-9cdd-4e05-b7b2-fec8ea7a4b3b" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>_CoordinateAxisType :</span></dt><dd>Lat</dd><dt><span>actual_range :</span></dt><dd>[-89.97916667  89.97916667]</dd><dt><span>axis :</span></dt><dd>Y</dd><dt><span>ioos_category :</span></dt><dd>Location</dd><dt><span>long_name :</span></dt><dd>Latitude</dd><dt><span>standard_name :</span></dt><dd>latitude</dd><dt><span>units :</span></dt><dd>degrees_north</dd><dt><span>valid_max :</span></dt><dd>89.97916666666667</dd><dt><span>valid_min :</span></dt><dd>-89.97916666666666</dd></dl></div><div class="xr-var-data"><pre>array([ 89.979167,  89.9375  ,  89.895833, ..., -89.895833, -89.9375  ,
       -89.979167])</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span class="xr-has-index">longitude</span></div><div class="xr-var-dims">(longitude)</div><div class="xr-var-dtype">float64</div><div class="xr-var-preview xr-preview">0.02083 0.0625 ... 359.9 360.0</div><input id="attrs-585c884f-597b-4f2f-921b-0a1d61e5eb92" class="xr-var-attrs-in" type="checkbox"><label for="attrs-585c884f-597b-4f2f-921b-0a1d61e5eb92" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-121bbed5-d093-4f6b-8ca1-d3035e760ad8" class="xr-var-data-in" type="checkbox"><label for="data-121bbed5-d093-4f6b-8ca1-d3035e760ad8" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>_CoordinateAxisType :</span></dt><dd>Lon</dd><dt><span>actual_range :</span></dt><dd>[2.08333333e-02 3.59979167e+02]</dd><dt><span>axis :</span></dt><dd>X</dd><dt><span>ioos_category :</span></dt><dd>Location</dd><dt><span>long_name :</span></dt><dd>Longitude</dd><dt><span>standard_name :</span></dt><dd>longitude</dd><dt><span>units :</span></dt><dd>degrees_east</dd><dt><span>valid_max :</span></dt><dd>359.97918701171875</dd><dt><span>valid_min :</span></dt><dd>0.020829999819397926</dd></dl></div><div class="xr-var-data"><pre>array([2.083333e-02, 6.250000e-02, 1.041667e-01, ..., 3.598958e+02,
       3.599375e+02, 3.599792e+02])</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-453f5924-f966-4824-a9a4-189307f96bd7" class="xr-section-summary-in" type="checkbox" checked=""><label for="section-453f5924-f966-4824-a9a4-189307f96bd7" class="xr-section-summary">Data variables: <span>(10)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-var-name"><span>chlor_a</span></div><div class="xr-var-dims">(time, latitude, longitude)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-4d7286e6-3b7b-48de-960c-1e1824687058" class="xr-var-attrs-in" type="checkbox"><label for="attrs-4d7286e6-3b7b-48de-960c-1e1824687058" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-58bd3eb9-b89a-4410-9547-a8288e3c4181" class="xr-var-data-in" type="checkbox"><label for="data-58bd3eb9-b89a-4410-9547-a8288e3c4181" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>ancillary_variables :</span></dt><dd>chlor_a_log10_rmsd chlor_a_log10_bias</dd><dt><span>colorBarMaximum :</span></dt><dd>30.0</dd><dt><span>colorBarMinimum :</span></dt><dd>0.03</dd><dt><span>colorBarScale :</span></dt><dd>Log</dd><dt><span>ioos_category :</span></dt><dd>Ocean Color</dd><dt><span>long_name :</span></dt><dd>Chlorophyll-a concentration in seawater (not log-transformed), generated by as a blended combination of OCI, OCI2, OC2 and OCx algorithms, depending on water class memberships</dd><dt><span>parameter_vocab_uri :</span></dt><dd>http://vocab.ndg.nerc.ac.uk/term/P011/current/CHLTVOLU</dd><dt><span>standard_name :</span></dt><dd>mass_concentration_of_chlorophyll_a_in_sea_water</dd><dt><span>units :</span></dt><dd>mg m-3</dd><dt><span>units_nonstandard :</span></dt><dd>mg m^-3</dd></dl></div><div class="xr-var-data"><pre>[11794636800 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>MERIS_nobs_sum</span></div><div class="xr-var-dims">(time, latitude, longitude)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-67491549-831a-4743-a897-2a9737bb8526" class="xr-var-attrs-in" type="checkbox"><label for="attrs-67491549-831a-4743-a897-2a9737bb8526" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-5ece24c6-9bbf-4f3e-8664-ca68721adc5c" class="xr-var-data-in" type="checkbox"><label for="data-5ece24c6-9bbf-4f3e-8664-ca68721adc5c" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>colorBarMaximum :</span></dt><dd>100.0</dd><dt><span>colorBarMinimum :</span></dt><dd>0.0</dd><dt><span>ioos_category :</span></dt><dd>Statistics</dd><dt><span>long_name :</span></dt><dd>Count of the number of observations from the MERIS sensor contributing to this bin cell</dd><dt><span>number_of_files_composited :</span></dt><dd>31</dd></dl></div><div class="xr-var-data"><pre>[11794636800 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>MODISA_nobs_sum</span></div><div class="xr-var-dims">(time, latitude, longitude)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-21e8a0fa-b647-46f3-8c3a-a5a211b34110" class="xr-var-attrs-in" type="checkbox"><label for="attrs-21e8a0fa-b647-46f3-8c3a-a5a211b34110" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-d8a6c060-2827-425a-aa1f-2e23ad6a3e1b" class="xr-var-data-in" type="checkbox"><label for="data-d8a6c060-2827-425a-aa1f-2e23ad6a3e1b" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>colorBarMaximum :</span></dt><dd>100.0</dd><dt><span>colorBarMinimum :</span></dt><dd>0.0</dd><dt><span>ioos_category :</span></dt><dd>Statistics</dd><dt><span>long_name :</span></dt><dd>Count of the number of observations from the MODIS (Aqua) sensor contributing to this bin cell</dd><dt><span>number_of_files_composited :</span></dt><dd>31</dd></dl></div><div class="xr-var-data"><pre>[11794636800 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>OLCI_A_nobs_sum</span></div><div class="xr-var-dims">(time, latitude, longitude)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-5a9e8c66-b52a-41b0-a9b4-2d75433d2b14" class="xr-var-attrs-in" type="checkbox"><label for="attrs-5a9e8c66-b52a-41b0-a9b4-2d75433d2b14" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-cb3f51b3-2ff4-491d-af30-0bf24c32e339" class="xr-var-data-in" type="checkbox"><label for="data-cb3f51b3-2ff4-491d-af30-0bf24c32e339" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>colorBarMaximum :</span></dt><dd>100.0</dd><dt><span>colorBarMinimum :</span></dt><dd>0.0</dd><dt><span>ioos_category :</span></dt><dd>Statistics</dd><dt><span>long_name :</span></dt><dd>Count of the number of observations from the OLCI (Sentinel-3a) sensor contributing to this bin cell</dd><dt><span>number_of_files_composited :</span></dt><dd>31</dd></dl></div><div class="xr-var-data"><pre>[11794636800 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>OLCI_B_nobs_sum</span></div><div class="xr-var-dims">(time, latitude, longitude)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-070b1912-1a1c-451e-a993-98161a2358d6" class="xr-var-attrs-in" type="checkbox"><label for="attrs-070b1912-1a1c-451e-a993-98161a2358d6" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-6d8753ea-4c71-4613-91fb-cdf032f66eab" class="xr-var-data-in" type="checkbox"><label for="data-6d8753ea-4c71-4613-91fb-cdf032f66eab" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>colorBarMaximum :</span></dt><dd>100.0</dd><dt><span>colorBarMinimum :</span></dt><dd>0.0</dd><dt><span>ioos_category :</span></dt><dd>Statistics</dd><dt><span>long_name :</span></dt><dd>Count of the number of observations from the OLCI (Sentinel-3b) sensor contributing to this bin cell</dd><dt><span>number_of_files_composited :</span></dt><dd>31</dd></dl></div><div class="xr-var-data"><pre>[11794636800 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>SeaWiFS_nobs_sum</span></div><div class="xr-var-dims">(time, latitude, longitude)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-d9ccfe11-d5ce-45c2-800e-3f560ee0d6f1" class="xr-var-attrs-in" type="checkbox"><label for="attrs-d9ccfe11-d5ce-45c2-800e-3f560ee0d6f1" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-61e1536f-1689-469d-b2e5-36c75f34e2f9" class="xr-var-data-in" type="checkbox"><label for="data-61e1536f-1689-469d-b2e5-36c75f34e2f9" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>colorBarMaximum :</span></dt><dd>100.0</dd><dt><span>colorBarMinimum :</span></dt><dd>0.0</dd><dt><span>ioos_category :</span></dt><dd>Statistics</dd><dt><span>long_name :</span></dt><dd>Count of the number of observations from the SeaWiFS (GAC and LAC) sensor contributing to this bin cell</dd><dt><span>number_of_files_composited :</span></dt><dd>31</dd></dl></div><div class="xr-var-data"><pre>[11794636800 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>VIIRS_nobs_sum</span></div><div class="xr-var-dims">(time, latitude, longitude)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-9b0def40-1df0-49de-b43b-6d1c0e06c641" class="xr-var-attrs-in" type="checkbox"><label for="attrs-9b0def40-1df0-49de-b43b-6d1c0e06c641" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-c7055128-3941-479d-945c-495f6158318f" class="xr-var-data-in" type="checkbox"><label for="data-c7055128-3941-479d-945c-495f6158318f" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>colorBarMaximum :</span></dt><dd>100.0</dd><dt><span>colorBarMinimum :</span></dt><dd>0.0</dd><dt><span>ioos_category :</span></dt><dd>Statistics</dd><dt><span>long_name :</span></dt><dd>Count of the number of observations from the VIIRS sensor contributing to this bin cell</dd><dt><span>number_of_files_composited :</span></dt><dd>31</dd></dl></div><div class="xr-var-data"><pre>[11794636800 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>chlor_a_log10_bias</span></div><div class="xr-var-dims">(time, latitude, longitude)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-dbaa9b4a-6d2f-488a-b1d9-41615167c1f4" class="xr-var-attrs-in" type="checkbox"><label for="attrs-dbaa9b4a-6d2f-488a-b1d9-41615167c1f4" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-944aa727-cbf3-4e3f-a9ac-8bcd8c1bfe8d" class="xr-var-data-in" type="checkbox"><label for="data-944aa727-cbf3-4e3f-a9ac-8bcd8c1bfe8d" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>colorBarMaximum :</span></dt><dd>0.1</dd><dt><span>colorBarMinimum :</span></dt><dd>-0.1</dd><dt><span>comment :</span></dt><dd>Uncertainty lookups derived from file: /data/datasets/CCI/v6.0-production/stage09b-uncertainty_tables/chlor_a/cci_chla_bias.dat</dd><dt><span>ioos_category :</span></dt><dd>Statistics</dd><dt><span>long_name :</span></dt><dd>Bias of log10-transformed chlorophyll-a concentration in seawater.</dd><dt><span>references :</span></dt><dd>https://esa-oceancolour-cci.org/?q=webfm_send/581</dd><dt><span>rel :</span></dt><dd>uncertainty</dd></dl></div><div class="xr-var-data"><pre>[11794636800 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>chlor_a_log10_rmsd</span></div><div class="xr-var-dims">(time, latitude, longitude)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-6732aff7-bdbb-451a-b181-80c392fc78d6" class="xr-var-attrs-in" type="checkbox"><label for="attrs-6732aff7-bdbb-451a-b181-80c392fc78d6" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-bedb0083-c329-4d6d-87e7-1b92dab9d9c2" class="xr-var-data-in" type="checkbox"><label for="data-bedb0083-c329-4d6d-87e7-1b92dab9d9c2" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>colorBarMaximum :</span></dt><dd>0.002</dd><dt><span>colorBarMinimum :</span></dt><dd>0.0</dd><dt><span>comment :</span></dt><dd>Uncertainty lookups derived from file: /data/datasets/CCI/v6.0-production/stage09b-uncertainty_tables/chlor_a/cci_chla_rmsd.dat</dd><dt><span>ioos_category :</span></dt><dd>Statistics</dd><dt><span>long_name :</span></dt><dd>Root-mean-square-difference of log10-transformed chlorophyll-a concentration in seawater.</dd><dt><span>references :</span></dt><dd>https://esa-oceancolour-cci.org/?q=webfm_send/581</dd><dt><span>rel :</span></dt><dd>uncertainty</dd></dl></div><div class="xr-var-data"><pre>[11794636800 values with dtype=float32]</pre></div></li><li class="xr-var-item"><div class="xr-var-name"><span>total_nobs_sum</span></div><div class="xr-var-dims">(time, latitude, longitude)</div><div class="xr-var-dtype">float32</div><div class="xr-var-preview xr-preview">...</div><input id="attrs-c29e2482-bbb5-4411-9240-fc2d1ff020a1" class="xr-var-attrs-in" type="checkbox"><label for="attrs-c29e2482-bbb5-4411-9240-fc2d1ff020a1" title="Show/Hide attributes"><svg class="icon xr-icon-file-text2"><use href="#icon-file-text2"></use></svg></label><input id="data-92aa4838-fbe4-421d-98af-41647165e143" class="xr-var-data-in" type="checkbox"><label for="data-92aa4838-fbe4-421d-98af-41647165e143" title="Show/Hide data repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-var-attrs"><dl class="xr-attrs"><dt><span>colorBarMaximum :</span></dt><dd>100.0</dd><dt><span>colorBarMinimum :</span></dt><dd>0.0</dd><dt><span>ioos_category :</span></dt><dd>Statistics</dd><dt><span>long_name :</span></dt><dd>Count of the total number of observations contributing to this bin cell</dd><dt><span>number_of_files_composited :</span></dt><dd>31</dd></dl></div><div class="xr-var-data"><pre>[11794636800 values with dtype=float32]</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-69e4a5fa-bc6d-4704-9645-905a252d4378" class="xr-section-summary-in" type="checkbox"><label for="section-69e4a5fa-bc6d-4704-9645-905a252d4378" class="xr-section-summary">Indexes: <span>(3)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><ul class="xr-var-list"><li class="xr-var-item"><div class="xr-index-name"><div>time</div></div><div class="xr-index-preview">PandasIndex</div><div></div><input id="index-cf89c3f8-9c41-4d79-b0a6-314b266b6c12" class="xr-index-data-in" type="checkbox"><label for="index-cf89c3f8-9c41-4d79-b0a6-314b266b6c12" title="Show/Hide index repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-index-data"><pre>PandasIndex(DatetimeIndex(['1997-09-04', '1997-10-01', '1997-11-01', '1997-12-01',
               '1998-01-01', '1998-02-01', '1998-03-01', '1998-04-01',
               '1998-05-01', '1998-06-01',
               ...
               '2023-03-01', '2023-04-01', '2023-05-01', '2023-06-01',
               '2023-07-01', '2023-08-01', '2023-09-01', '2023-10-01',
               '2023-11-01', '2023-12-01'],
              dtype='datetime64[ns]', name='time', length=316, freq=None))</pre></div></li><li class="xr-var-item"><div class="xr-index-name"><div>latitude</div></div><div class="xr-index-preview">PandasIndex</div><div></div><input id="index-b1f86011-ab9e-494f-a4d8-817beb7e97a6" class="xr-index-data-in" type="checkbox"><label for="index-b1f86011-ab9e-494f-a4d8-817beb7e97a6" title="Show/Hide index repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-index-data"><pre>PandasIndex(Index([ 89.97916666666667,            89.9375,  89.89583333333333,
        89.85416666666667,            89.8125,  89.77083333333333,
        89.72916666666667,            89.6875,  89.64583333333333,
        89.60416666666667,
       ...
       -89.60416666666666, -89.64583333333331,           -89.6875,
       -89.72916666666666, -89.77083333333331,           -89.8125,
       -89.85416666666666, -89.89583333333331,           -89.9375,
       -89.97916666666666],
      dtype='float64', name='latitude', length=4320))</pre></div></li><li class="xr-var-item"><div class="xr-index-name"><div>longitude</div></div><div class="xr-index-preview">PandasIndex</div><div></div><input id="index-11dfba14-37ac-4a85-9bbe-8e7e8c43965b" class="xr-index-data-in" type="checkbox"><label for="index-11dfba14-37ac-4a85-9bbe-8e7e8c43965b" title="Show/Hide index repr"><svg class="icon xr-icon-database"><use href="#icon-database"></use></svg></label><div class="xr-index-data"><pre>PandasIndex(Index([0.020833333333314386,               0.0625,  0.10416666666665719,
        0.14583333333331439,               0.1875,   0.2291666666666572,
         0.2708333333333144,               0.3125,   0.3541666666666572,
         0.3958333333333144,
       ...
         359.60416666666663,    359.6458333333333,             359.6875,
         359.72916666666663,    359.7708333333333,             359.8125,
         359.85416666666663,    359.8958333333333,             359.9375,
         359.97916666666663],
      dtype='float64', name='longitude', length=8640))</pre></div></li></ul></div></li><li class="xr-section-item"><input id="section-e9414aeb-d3fa-412d-81c6-1ea8c82a80bc" class="xr-section-summary-in" type="checkbox"><label for="section-e9414aeb-d3fa-412d-81c6-1ea8c82a80bc" class="xr-section-summary">Attributes: <span>(53)</span></label><div class="xr-section-inline-details"></div><div class="xr-section-details"><dl class="xr-attrs"><dt><span>cdm_data_type :</span></dt><dd>Grid</dd><dt><span>comment :</span></dt><dd>See summary attribute</dd><dt><span>Conventions :</span></dt><dd>CF-1.7, COARDS, ACDD-1.3</dd><dt><span>creation_date :</span></dt><dd>Thu Jan 18 09:04:18 2024</dd><dt><span>creator_email :</span></dt><dd>help@esa-oceancolour-cci.org</dd><dt><span>creator_name :</span></dt><dd>Plymouth Marine Laboratory</dd><dt><span>creator_url :</span></dt><dd>https://esa-oceancolour-cci.org</dd><dt><span>date_created :</span></dt><dd>2022-08-15T22:03:48Z</dd><dt><span>Easternmost_Easting :</span></dt><dd>359.97916666666663</dd><dt><span>geospatial_lat_max :</span></dt><dd>89.97916666666667</dd><dt><span>geospatial_lat_min :</span></dt><dd>-89.97916666666666</dd><dt><span>geospatial_lat_resolution :</span></dt><dd>0.041666666666666664</dd><dt><span>geospatial_lat_units :</span></dt><dd>degrees_north</dd><dt><span>geospatial_lon_max :</span></dt><dd>359.97916666666663</dd><dt><span>geospatial_lon_min :</span></dt><dd>0.020833333333314386</dd><dt><span>geospatial_lon_resolution :</span></dt><dd>0.041666666666666664</dd><dt><span>geospatial_lon_units :</span></dt><dd>degrees_east</dd><dt><span>git_commit_hash :</span></dt><dd>27964270df6ae0b9bdd0af5672529dbebb4e7bd9</dd><dt><span>history :</span></dt><dd>Thu Jan 18 08:21:00 2024: ncatted -O -a geospatial_lon_max,global,o,f,360.0 ESACCI-OC-L3S-CHLOR_A-MERGED-1M_MONTHLY_4km_GEO_PML_OCx-202312-fv6.0-0-360.nc
Thu Jan 18 08:21:00 2024: ncatted -O -a geospatial_lon_min,global,o,f,0.0 ESACCI-OC-L3S-CHLOR_A-MERGED-1M_MONTHLY_4km_GEO_PML_OCx-202312-fv6.0-0-360.nc
Thu Jan 18 08:21:00 2024: ncatted -O -a valid_max,lon,o,f,359.9792 ESACCI-OC-L3S-CHLOR_A-MERGED-1M_MONTHLY_4km_GEO_PML_OCx-202312-fv6.0-0-360.nc
Thu Jan 18 08:21:00 2024: ncatted -O -a valid_min,lon,o,f,0.02083 ESACCI-OC-L3S-CHLOR_A-MERGED-1M_MONTHLY_4km_GEO_PML_OCx-202312-fv6.0-0-360.nc
Thu Jan 18 08:20:41 2024: ncap2 -O -s where(lon&lt;0) lon=lon+360 ESACCI-OC-L3S-CHLOR_A-MERGED-1M_MONTHLY_4km_GEO_PML_OCx-202312-fv6.0-0-360.nc ESACCI-OC-L3S-CHLOR_A-MERGED-1M_MONTHLY_4km_GEO_PML_OCx-202312-fv6.0-0-360.nc
Thu Jan 18 08:20:20 2024: ncks -O --msa_usr_rdr -d lon,0.0,180.0 -d lon,-180.0,0.0 ESACCI-OC-L3S-CHLOR_A-MERGED-1M_MONTHLY_4km_GEO_PML_OCx-202312-fv6.0.nc ESACCI-OC-L3S-CHLOR_A-MERGED-1M_MONTHLY_4km_GEO_PML_OCx-202312-fv6.0-0-360.nc
Source data were: ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231201-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231202-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231203-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231204-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231205-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231206-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231207-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231208-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231209-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231210-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231211-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231212-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231213-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231214-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231215-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231216-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231217-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231218-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231219-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231220-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231221-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231222-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231223-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231224-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231225-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231226-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231227-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231228-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231229-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231230-fv6.0.nc, ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1D_DAILY_4km_GEO_PML_OCx_QAA-20231231-fv6.0.nc; netcdf_compositor_cci composites  Rrs_412, Rrs_412_bias, Rrs_443, Rrs_443_bias, Rrs_490, Rrs_490_bias, Rrs_510, Rrs_510_bias, Rrs_560, Rrs_560_bias, Rrs_665, Rrs_665_bias, adg_412, adg_412_bias, adg_443, adg_443_bias, adg_490, adg_490_bias, adg_510, adg_510_bias, adg_560, adg_560_bias, adg_665, adg_665_bias, aph_412, aph_412_bias, aph_443, aph_443_bias, aph_490, aph_490_bias, aph_510, aph_510_bias, aph_560, aph_560_bias, aph_665, aph_665_bias, atot_412, atot_443, atot_490, atot_510, atot_560, atot_665, bbp_412, bbp_443, bbp_490, bbp_510, bbp_560, bbp_665, chlor_a, chlor_a_log10_bias, kd_490, kd_490_bias, water_class1, water_class10, water_class11, water_class12, water_class13, water_class14, water_class2, water_class3, water_class4, water_class5, water_class6, water_class7, water_class8, water_class9 with --mean,  Rrs_412_rmsd, Rrs_443_rmsd, Rrs_490_rmsd, Rrs_510_rmsd, Rrs_560_rmsd, Rrs_665_rmsd, adg_412_rmsd, adg_443_rmsd, adg_490_rmsd, adg_510_rmsd, adg_560_rmsd, adg_665_rmsd, aph_412_rmsd, aph_443_rmsd, aph_490_rmsd, aph_510_rmsd, aph_560_rmsd, aph_665_rmsd, chlor_a_log10_rmsd, kd_490_rmsd with --root-mean-square, and  MERIS_nobs, MODISA_nobs, OLCI-A_nobs, OLCI-B_nobs, SeaWiFS_nobs, VIIRS_nobs, total_nobs - with --total
1705571341 Subsetted from standardised_geo/ESACCI-OC-L3S-OC_PRODUCTS-MERGED-1M_MONTHLY_4km_GEO_PML_OCx_QAA-202312-fv6.0.nc to only include variables MERIS_nobs_sum,MODISA_nobs_sum,OLCI-A_nobs_sum,OLCI-B_nobs_sum,SeaWiFS_nobs_sum,VIIRS_nobs_sum,chlor_a,chlor_a_log10_bias,chlor_a_log10_rmsd,crs,lat,lon,time,total_nobs_sum
2024-03-15T14:27:48Z (local files)
2024-03-15T14:27:48Z https://oceanwatch.pifsc.noaa.gov/erddap/griddap/esa-cci-chla-monthly-v6-0.das</dd><dt><span>id :</span></dt><dd>ESACCI-OC-L3S-CHLOR_A-MERGED-1M_MONTHLY_4km_GEO_PML_OCx-202312-fv6.0.nc</dd><dt><span>infoUrl :</span></dt><dd>https://esa-oceancolour-cci.org/</dd><dt><span>institution :</span></dt><dd>Plymouth Marine Laboratory</dd><dt><span>keywords :</span></dt><dd>algorithms, aqua, area, array, array-data, bias, bin, blended, cci, cell, chemistry, chlor_a, chlor_a_log10_bias, chlor_a_log10_rmsd, chlorophyll, chlorophyll-a, class, color, colour, combination, comprehensive, concentration, contributing, count, coverage, data, depending, difference, earth, Earth Science &gt; Oceans &gt; Ocean Chemistry &gt; Chlorophyll, esa, field, field-of-view, gac, generated, global, imager, imager/radiometer, imaging, infrared, laboratory, lac, large, local, log, log-transformed, log10, log10-transformed, marine, mass, mass_concentration_of_chlorophyll_a_in_sea_water, mean, memberships, meris, MERIS_nobs_sum, moderate, modis, MODISA_nobs_sum, not, number, observation, observations, oc2, ocean, ocean color, ocean colour, oceans, oci, oci2, ocx, olci, OLCI-A_nobs_sum, OLCI-B_nobs_sum, plymouth, product, radiometer, resolution, root, root-mean-square-difference, satellite, science, sea, sea-wide, seawater, seawifs, SeaWiFS_nobs_sum, sensor, sentinel, sentinel-3a, sentinel-3b, spectroradiometer, square, statistics, stewardship, suite, system, time, total, total_nobs_sum, transformed, view, viirs, VIIRS_nobs_sum, visible, water, wide</dd><dt><span>keywords_vocabulary :</span></dt><dd>GCMD Science Keywords</dd><dt><span>license :</span></dt><dd>ESA CCI Data Policy: free and open access.  When referencing, please use: Ocean Colour Climate Change Initiative dataset, Version &lt;Version Number&gt;, European Space Agency, available online at https://esa-oceancolour-cci.org.  We would also appreciate being notified of publications so that we can list them on the project website at https://esa-oceancolour-cci.org/?q=publications</dd><dt><span>naming_authority :</span></dt><dd>uk.ac.pml</dd><dt><span>NCO :</span></dt><dd>netCDF Operators version 4.7.5 (Homepage = http://nco.sf.net, Code = https://github.com/nco/nco)</dd><dt><span>nco_openmp_thread_number :</span></dt><dd>1</dd><dt><span>netcdf_file_type :</span></dt><dd>NETCDF4_CLASSIC</dd><dt><span>Northernmost_Northing :</span></dt><dd>89.97916666666667</dd><dt><span>number_of_bands_used_to_classify :</span></dt><dd>4</dd><dt><span>number_of_files_composited :</span></dt><dd>31</dd><dt><span>number_of_optical_water_types :</span></dt><dd>14</dd><dt><span>platform :</span></dt><dd>Orbview-2,Aqua,Envisat,Suomi-NPP, Sentinel-3a, Sentinel-3b</dd><dt><span>processing_level :</span></dt><dd>Level-3</dd><dt><span>product_version :</span></dt><dd>6.0</dd><dt><span>project :</span></dt><dd>Climate Change Initiative - European Space Agency</dd><dt><span>references :</span></dt><dd>https://esa-oceancolour-cci.org/</dd><dt><span>sensor :</span></dt><dd>SeaWiFS,MODIS,MERIS,VIIRS,OLCI</dd><dt><span>sensors_present :</span></dt><dd>OLCIa OLCIb</dd><dt><span>source :</span></dt><dd>NASA SeaWiFS  L1A and L2 R2018.0 LAC and GAC, MODIS-Aqua L1A and L2 R2018.0, MERIS L1B 3rd reprocessing inc OCL corrections, NASA VIIRS L1A and L2 R2018.0, OLCI L1B</dd><dt><span>sourceUrl :</span></dt><dd>(local files)</dd><dt><span>Southernmost_Northing :</span></dt><dd>-89.97916666666666</dd><dt><span>spatial_resolution :</span></dt><dd>4km nominal at equator</dd><dt><span>standard_name_vocabulary :</span></dt><dd>CF Standard Name Table v70</dd><dt><span>summary :</span></dt><dd>Data products generated by the Ocean Colour component of the European Space Agency Climate Change Initiative project. These files are monthly composites of merged sensor (MERIS, Moderate Resolution Imaging Spectroradiometer (MODIS) Aqua, Sea-Wide Field-of-View Sensor (SeaWiFS) Local Area Coverage (LAC) &amp; Global Area Coverage (GAC), Visible and Infrared Imager/Radiometer Suite (VIIRS), OLCI) products.  MODIS Aqua and SeaWiFS were band-shifted and bias-corrected to MERIS bands and values using a temporally and spatially varying scheme based on the overlap years of 2003-2007.  VIIRS was band-shifted and bias-corrected in a second stage against the MODIS Rrs that had already been corrected to MERIS levels, for the overlap period 2012-2014; at the third stage Sentinel-3A OLCI was bias corrected against already corrected MODIS, for overlap period 2016-07-01 to 2019-06-30;  at the fourth stage Sentinel-3B OLCI was bias corrected against already corrected Sentinel-3A OLCI, for overlap period 2018-07-01 to 2021-06-30.  VIIRS, MODIS, SeaWiFS and MERIS Rrs were derived from a combination of NASA's l2gen (for basic sensor geometry corrections, etc) and HYGEOS POLYMER (for atmospheric correction). OLCI Rrs were sourced at L1b (already geometrically corrected) and processed with POLYMER.  The Rrs were binned to a sinusoidal 4km level-3 grid, and later to 4km geographic projection, by Brockmann Consult's SNAP.  Derived products were generally computed with the standard algorithms through SeaDAS.  QAA IOPs were derived using the standard SeaDAS algorithm but with a modified backscattering table to match that used in the bandshifting.  The final chlorophyll is a combination of OCI, OCI2, OC2 and OCx, depending on the water class memberships.  Uncertainty estimates were added using the fuzzy water classifier and uncertainty estimation algorithm of Tim Moore as documented in Jackson et al (2017). and updated according to Jackson et al. (in prep).</dd><dt><span>time_coverage_duration :</span></dt><dd>P1M</dd><dt><span>time_coverage_end :</span></dt><dd>2023-12-01T00:00:00Z</dd><dt><span>time_coverage_resolution :</span></dt><dd>P1M</dd><dt><span>time_coverage_start :</span></dt><dd>1997-09-04T00:00:00Z</dd><dt><span>title :</span></dt><dd>Chlorophyll a concentration, ESA OC CCI - Monthly, 1997-present. v6.0</dd><dt><span>tracking_id :</span></dt><dd>abd52a4c-7009-464f-b1eb-958f7d333a1d</dd><dt><span>Westernmost_Easting :</span></dt><dd>0.020833333333314386</dd></dl></div></li></ul></div></div>
</div>
</div>
<p><strong>Opening the dataset in Xarray lets you look at the dataset metadata.</strong><br>
* The metadata are listed above. * No data is downloaded until you request it.</p>
<p><strong>From the metadata you can view:</strong> * The coordinates (time, latitude and longitude) that you will use to select the data to download. * A list of ten data variables. For this exercise, we want the “chlor_a” variable. If you want, you can find out about each variable with clicking the page icon to the right of each variable name.</p>
<p><strong>A note on dataset selection</strong><br>
We have preselected the OC-CCI monthly dataset because we know it will work with this exercise. If you were selecting datasets on your own, you would want to check out the dataset to determine if its spatial and temporal coverages are suitable for your application.</p>
<p>You can find that information above by clicking the right arrow next to “Attribute”. Then look through the list to find: * ‘time_coverage_start’ and ‘time_coverage_end’: the time range * ‘geospatial_lat_min’ and ‘geospatial_lat_max’: the latitude range * ‘geospatial_lon_min’ and ‘geospatial_lon_max’: the longitude range</p>
<p>There are a lot of metadata attributes to look through. We can make it easier with a little code to print out the metadata of interest. Then compare these ranges to those found in your track data.</p>
<div id="cell-14" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Temporal and spatial ranges of the satellite dataset'</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'time range'</span>, ds.attrs[<span class="st">'time_coverage_start'</span>], </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>      ds.attrs[<span class="st">'time_coverage_end'</span>])</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'latitude range'</span>, ds.attrs[<span class="st">'geospatial_lat_min'</span>], </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>      ds.attrs[<span class="st">'geospatial_lat_max'</span>])</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'longitude range'</span>, ds.attrs[<span class="st">'geospatial_lon_min'</span>], </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>      ds.attrs[<span class="st">'geospatial_lon_max'</span>])</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">' '</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Temporal and spatial ranges of the track data'</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'time range'</span>, df.year_month_day.<span class="bu">min</span>(), df.year_month_day.<span class="bu">max</span>())</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'latitude range'</span>, </span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>      <span class="bu">round</span>(df.mean_lat.<span class="bu">min</span>(), <span class="dv">2</span>), <span class="bu">round</span>(df.mean_lat.<span class="bu">max</span>(), <span class="dv">2</span>))</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'longitude range'</span>, </span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>      <span class="bu">round</span>(df.mean_lon.<span class="bu">min</span>(), <span class="dv">2</span>), <span class="bu">round</span>(df.mean_lon.<span class="bu">max</span>(), <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Temporal and spatial ranges of the satellite dataset
time range 1997-09-04T00:00:00Z 2023-12-01T00:00:00Z
latitude range -89.97916666666666 89.97916666666667
longitude range 0.020833333333314386 359.97916666666663
 
Temporal and spatial ranges of the track data
time range 2005-05-04 00:00:00 2008-08-16 00:00:00
latitude range 23.72 41.77
longitude range 175.86 248.57</code></pre>
</div>
</div>
</section>
<section id="download-the-satellite-data-that-corresponds-to-each-track-location" class="level3">
<h3 class="anchored" data-anchor-id="download-the-satellite-data-that-corresponds-to-each-track-location">Download the satellite data that corresponds to each track location</h3>
<div id="cell-16" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a temporary Pandas data frame to hold the downloaded satellite data</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>col_names <span class="op">=</span> [<span class="st">"erddap_date"</span>, <span class="st">"matched_lat"</span>, <span class="st">"matched_lon"</span>, <span class="st">"matched_chla"</span>]</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>tot <span class="op">=</span> pd.DataFrame(columns<span class="op">=</span>col_names)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Finish each URL and download</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="bu">len</span>(df)):</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    clear_output(wait<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(i<span class="op">+</span><span class="dv">1</span>, <span class="st">'of'</span>, <span class="bu">len</span>(df))</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Crop the dataset to include data that corresponds to track locations</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    cropped_ds <span class="op">=</span> ds[<span class="st">'chlor_a'</span>].sel(time<span class="op">=</span>df.year_month_day[i],</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>                                   latitude<span class="op">=</span>df.mean_lat[i],</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>                                   longitude<span class="op">=</span>df.mean_lon[i],</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>                                   method<span class="op">=</span><span class="st">'nearest'</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>                                   )</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>     </span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Downloaded the data and add it to a new line in the tot data frame</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>    tot.loc[<span class="bu">len</span>(tot.index)] <span class="op">=</span> [cropped_ds.time.values,</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>                               np.<span class="bu">round</span>(cropped_ds.latitude.values, <span class="dv">5</span>),  <span class="co"># round 5 dec</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>                               np.<span class="bu">round</span>(cropped_ds.longitude.values, <span class="dv">5</span>), <span class="co"># round 5 dec</span></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>                               np.<span class="bu">round</span>(cropped_ds.values, <span class="dv">2</span>)  <span class="co"># round 2 decimals</span></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>                               ]</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(tot.loc[[<span class="bu">len</span>(tot)<span class="op">-</span><span class="dv">1</span>]])</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>tot.head(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>25 of 25
   erddap_date  matched_lat  matched_lon  matched_chla
24  2008-08-01     26.77083    245.77083          0.71</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">erddap_date</th>
<th data-quarto-table-cell-role="th">matched_lat</th>
<th data-quarto-table-cell-role="th">matched_lon</th>
<th data-quarto-table-cell-role="th">matched_chla</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2005-05-01</td>
<td>32.6875</td>
<td>176.60417</td>
<td>0.29</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2005-07-01</td>
<td>35.0625</td>
<td>175.85417</td>
<td>0.11</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="consolidate-the-downloaded-satellite-data-into-the-track-data-frame" class="level3">
<h3 class="anchored" data-anchor-id="consolidate-the-downloaded-satellite-data-into-the-track-data-frame">Consolidate the downloaded satellite data into the track data frame</h3>
<div id="cell-18" class="cell" data-scrolled="true" data-execution_count="9">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>df[[<span class="st">'matched_lat'</span>, </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'matched_lon'</span>, </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'matched_chla'</span>, </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'erddap_date'</span>]] <span class="op">=</span> tot[[<span class="st">'matched_lat'</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>                           <span class="st">'matched_lon'</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>                           <span class="st">'matched_chla'</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>                           <span class="st">'erddap_date'</span>]]</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>df.head(<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">year_month_day</th>
<th data-quarto-table-cell-role="th">mean_lon</th>
<th data-quarto-table-cell-role="th">mean_lat</th>
<th data-quarto-table-cell-role="th">matched_lat</th>
<th data-quarto-table-cell-role="th">matched_lon</th>
<th data-quarto-table-cell-role="th">matched_chla</th>
<th data-quarto-table-cell-role="th">erddap_date</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2005-05-04</td>
<td>176.619433</td>
<td>32.678728</td>
<td>32.6875</td>
<td>176.60417</td>
<td>0.29</td>
<td>2005-05-01</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2005-06-23</td>
<td>175.860895</td>
<td>35.057734</td>
<td>35.0625</td>
<td>175.85417</td>
<td>0.11</td>
<td>2005-07-01</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="save-your-work" class="level3">
<h3 class="anchored" data-anchor-id="save-your-work">Save your work</h3>
<div id="cell-20" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>df.to_csv(<span class="st">'chl_matchup_turtle25327.csv'</span>, index<span class="op">=</span><span class="va">False</span>, encoding<span class="op">=</span><span class="st">'utf-8'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="plot-chlorophyll-matchup-data-onto-a-map" class="level2">
<h2 class="anchored" data-anchor-id="plot-chlorophyll-matchup-data-onto-a-map">Plot chlorophyll matchup data onto a map</h2>
<section id="first-plot-a-histogram-of-the-chlorophyll-data" class="level3">
<h3 class="anchored" data-anchor-id="first-plot-a-histogram-of-the-chlorophyll-data">First plot a histogram of the chlorophyll data</h3>
<div id="cell-23" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Range:'</span>, df.matched_chla.<span class="bu">min</span>(), df.matched_chla.<span class="bu">max</span>())</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>_ <span class="op">=</span> df.matched_chla.hist(bins<span class="op">=</span><span class="dv">40</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Range: 0.06 0.71</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="satellite_matchups_to_track_locations_xarray_files/figure-html/cell-11-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The range of chlorophyll values can be large, with lots of very low values and a few very high values. Using a linear color bar, most of the lower values would have the same color. * To better visualize the data, we often plot the log or log10 of chlorophyll.</p>
</section>
<section id="plot-a-histogram-of-the-log-of-the-chlorophyll-data" class="level3">
<h3 class="anchored" data-anchor-id="plot-a-histogram-of-the-log-of-the-chlorophyll-data">Plot a histogram of the log of the chlorophyll data</h3>
<div id="cell-25" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Range:'</span>, np.log(df.matched_chla.<span class="bu">min</span>()), np.log(df.matched_chla.<span class="bu">max</span>()))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>_ <span class="op">=</span> np.log(df.matched_chla).hist(bins<span class="op">=</span><span class="dv">40</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Range: -2.8134108 -0.34249032</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="satellite_matchups_to_track_locations_xarray_files/figure-html/cell-12-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The logarithmic transformation displays the range of values across the color bar range (above).</li>
</ul>
</section>
<section id="map-the-chlorophyll-data" class="level3">
<h3 class="anchored" data-anchor-id="map-the-chlorophyll-data">Map the chlorophyll data</h3>
<div id="cell-28" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">10</span>))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Label axes of a Plate Carree projection with a central longitude of 180:</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># set the projection</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>ax1 <span class="op">=</span> plt.subplot(<span class="dv">211</span>, projection<span class="op">=</span>ccrs.PlateCarree(central_longitude<span class="op">=</span><span class="dv">180</span>))</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the lon and lat ranges to set the extent of the map</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="co"># the 120, 260 lon range will show the whole Pacific</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="co"># the 15, 55 lat range with capture the range of the data</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>ax1.set_extent([<span class="dv">120</span>,<span class="dv">255</span>, <span class="dv">15</span>, <span class="dv">55</span>], ccrs.PlateCarree())</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a><span class="co"># set the tick marks to be slightly inside the map extents</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>ax1.set_xticks(<span class="bu">range</span>(<span class="dv">120</span>,<span class="dv">255</span>,<span class="dv">20</span>), crs<span class="op">=</span>ccrs.PlateCarree())</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>ax1.set_yticks(<span class="bu">range</span>(<span class="dv">20</span>,<span class="dv">50</span>,<span class="dv">10</span>), crs<span class="op">=</span>ccrs.PlateCarree())</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Add geographical features</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>ax1.add_feature(cfeature.LAND, facecolor<span class="op">=</span><span class="st">'0.6'</span>)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>ax1.coastlines()</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a><span class="co"># format the lat and lon axis labels</span></span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>lon_formatter <span class="op">=</span> LongitudeFormatter(zero_direction_label<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>lat_formatter <span class="op">=</span> LatitudeFormatter()</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>ax1.xaxis.set_major_formatter(lon_formatter)</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>ax1.yaxis.set_major_formatter(lat_formatter)</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a><span class="co"># build and plot coordinates onto map</span></span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>x,y <span class="op">=</span> <span class="bu">list</span>(df.mean_lon),<span class="bu">list</span>(df.mean_lat)</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>ax1 <span class="op">=</span> plt.scatter(x, y, transform<span class="op">=</span>ccrs.PlateCarree(),</span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>                  marker<span class="op">=</span><span class="st">'o'</span>,</span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a>                  c<span class="op">=</span>np.log(df.matched_chla),</span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a>                  cmap<span class="op">=</span>plt.get_cmap(<span class="st">'jet'</span>)</span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a>                  )</span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a>ax1<span class="op">=</span>plt.plot(x[<span class="dv">0</span>],y[<span class="dv">0</span>],marker<span class="op">=</span><span class="st">'*'</span>, transform<span class="op">=</span>ccrs.PlateCarree(), markersize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a>ax1<span class="op">=</span>plt.plot(x[<span class="op">-</span><span class="dv">1</span>],y[<span class="op">-</span><span class="dv">1</span>],marker<span class="op">=</span><span class="st">'X'</span>, transform<span class="op">=</span>ccrs.PlateCarree(), markersize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-37"><a href="#cb18-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-38"><a href="#cb18-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-39"><a href="#cb18-39" aria-hidden="true" tabindex="-1"></a><span class="co"># control color bar values spacing</span></span>
<span id="cb18-40"><a href="#cb18-40" aria-hidden="true" tabindex="-1"></a>levs2 <span class="op">=</span> np.arange(<span class="op">-</span><span class="fl">2.5</span>, <span class="dv">0</span>, <span class="fl">0.5</span>)</span>
<span id="cb18-41"><a href="#cb18-41" aria-hidden="true" tabindex="-1"></a>cbar<span class="op">=</span>plt.colorbar(ticks<span class="op">=</span>levs2, shrink<span class="op">=</span><span class="fl">0.75</span>, aspect<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb18-42"><a href="#cb18-42" aria-hidden="true" tabindex="-1"></a>cbar.set_label(<span class="st">"Chl a (mg/m^3)"</span>, size<span class="op">=</span><span class="dv">15</span>, labelpad<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb18-43"><a href="#cb18-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-44"><a href="#cb18-44" aria-hidden="true" tabindex="-1"></a><span class="co"># set the labels to be exp(levs2) so the label reflect values of chl-a, not log(chl-a)</span></span>
<span id="cb18-45"><a href="#cb18-45" aria-hidden="true" tabindex="-1"></a>cbar.ax.set_yticklabels(np.around(np.exp(levs2), <span class="dv">2</span>), size<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb18-46"><a href="#cb18-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-47"><a href="#cb18-47" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Chlorophyll Matchup to Animal Track #25317"</span>, size<span class="op">=</span><span class="dv">15</span>)</span>
<span id="cb18-48"><a href="#cb18-48" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="satellite_matchups_to_track_locations_xarray_files/figure-html/cell-13-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="on-your-own" class="level2">
<h2 class="anchored" data-anchor-id="on-your-own">On your own!</h2>
<section id="exercise-1" class="level5">
<h5 class="anchored" data-anchor-id="exercise-1">Exercise 1:</h5>
<p>Repeat the steps above with a different dataset. For example, extract sea surface temperature data using the NOAA Geo-polar Blended Analysis SST, GHRSST dataset: https://coastwatch.pfeg.noaa.gov/erddap/griddap/nesdisGeoPolarSSTN5NRT_Lon0360.html<br>
* This dataset is a different ERDDAP; It has a different base URL and dataset ID and variable name. * Check the metadata to make sure the dataset covers the spatial and temporal range of the track dataset.</p>
</section>
<section id="exercise-2" class="level5">
<h5 class="anchored" data-anchor-id="exercise-2">Exercise 2:</h5>
<p>Go to an ERDDAP of your choice, find a dataset of interest, generate the URL, copy it and edit the script above to run a match up on that dataset. To find other ERDDAP servers, you can use this search engine: http://erddap.com/<br>
* This dataset will likely be on a different base URL and dataset ID and variable name. * Check the metadata to make sure the dataset covers the spatial and temporal range of the track dataset.</p>
</section>
<section id="optional" class="level5">
<h5 class="anchored" data-anchor-id="optional">Optional</h5>
<p>Repeat the steps above with a daily version of the OC-CCI dataset to see how cloud cover can reduce the data you retrieve. https://oceanwatch.pifsc.noaa.gov/erddap/griddap/CRW_sst_v1_0.html</p>
</section>
</section>
<section id="match-satellite-chlorophyll-to-dusky-shark-telemetry" class="level1">
<h1>Match satellite chlorophyll to Dusky shark telemetry</h1>
<p>The turtle example above selects a single nearest satellite pixel at each track point. In many real-world applications, it can be useful to match a small neighborhood of pixels around each location and summarize the satellite values (e.g.&nbsp;mean chlorophyll with ±0.2°). This helps reduce noise from single-pixel values and can better represent local conditions.</p>
<p>In this example, we:</p>
<ul>
<li>Load dusky shark tag detections (lon, lat, date)</li>
<li>Open a gridded chlorophyll dataset using Xarray (OPenDAP)</li>
<li>For each detection:
<ul>
<li>select the nearest satellite time</li>
<li>extract ±0.2° window in lon/lat</li>
<li>compute mean, standard deviation, and valid pixel count</li>
</ul></li>
</ul>
<p><strong>Data note:</strong> These dusky shark data were collected and provided by Dr.&nbsp;Chuck Bangley (Smithsonian Environmental Research Center). For details, see:</p>
<pre><code>Bangley, C.W., et al. (2020) Identifying Important Juvenile Dusky Shark Habitat in the Northwest Atlantic Ocean Using Acoustic Telemetry and Spatial Modeling. Marine and Coastal Fisheries, 12:348–363. DOI: 10.1002/mcf2.10120</code></pre>
<section id="load-dusky-shark-telemetry-data" class="level2">
<h2 class="anchored" data-anchor-id="load-dusky-shark-telemetry-data">Load Dusky shark telemetry data</h2>
<p>Load the dusky shark acoustic telemetry detections, which include longitude, latitude, detection date, and transmitter ID. Each row represents a single shark detection that will be matched to satellite data.</p>
<div id="cell-32" class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load shark tag data (lon, lat, date, transmitter ID)</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>tag_path <span class="op">=</span> os.path.join(<span class="st">'..'</span>,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                          <span class="st">'resources'</span>,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>                          <span class="st">'DuskyDaily_NOAAclass_sortedTransmitterDate.csv'</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>tags <span class="op">=</span> pd.read_csv(tag_path)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(tags.head(<span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Transmitter       Date  Latitude  Longitude  Unnamed: 4  \
0  A69-1601-46065  9/15/2017  38.22503  -75.03418         NaN   
1  A69-1601-46065  9/27/2017  38.30890  -75.01166         NaN   
2  A69-1601-46065  10/2/2017  38.30890  -75.01166         NaN   

  Unique Transmitters  
0      A69-9006-16095  
1      A69-9001-16950  
2      A69-9006-16094  </code></pre>
</div>
</div>
</section>
<section id="convert-telemetry-columns-to-coordinate-arrays" class="level2">
<h2 class="anchored" data-anchor-id="convert-telemetry-columns-to-coordinate-arrays">Convert telemetry columns to coordinate arrays</h2>
<p>Longitude, latitude, and detection dates are extracted and converted into NumPy arrays and datetime objects. This format is required for iterating over detections and selecting satellite data by time.</p>
<div id="cell-34" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert columns to arrays (same pattern used earlier in this tutorial)</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>xcoord <span class="op">=</span> tags[<span class="st">"Longitude"</span>].to_numpy()</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>ycoord <span class="op">=</span> tags[<span class="st">"Latitude"</span>].to_numpy()</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>tcoord <span class="op">=</span> pd.to_datetime(tags[<span class="st">"Date"</span>], <span class="bu">format</span><span class="op">=</span><span class="st">"%m/</span><span class="sc">%d</span><span class="st">/%Y"</span>).to_numpy()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="open-a-satellite-dataset-using-xarray-opendap" class="level2">
<h2 class="anchored" data-anchor-id="open-a-satellite-dataset-using-xarray-opendap">Open a satellite dataset using Xarray (OPeNDAP)</h2>
<p>For this example, we use a CoastWatch MODIS 8-day chlorophyll dataset</p>
<div id="cell-36" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>erddap_url2 <span class="op">=</span> <span class="st">'/'</span>.join([<span class="st">'https://coastwatch.pfeg.noaa.gov/'</span>,</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>                       <span class="st">'erddap'</span>,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>                       <span class="st">'griddap'</span>,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>                       <span class="st">'erdMH1chla8day'</span>])</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>ds_shark <span class="op">=</span> xr.open_dataset(erddap_url2)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>ds_shark</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Temporal and spatial ranges of the satellite dataset"</span>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"time range"</span>, ds_shark.attrs[<span class="st">"time_coverage_start"</span>], ds_shark.attrs[<span class="st">"time_coverage_end"</span>])</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"latitude range"</span>, ds_shark.attrs[<span class="st">"geospatial_lat_min"</span>], ds_shark.attrs[<span class="st">"geospatial_lat_max"</span>])</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"longitude range"</span>, ds_shark.attrs[<span class="st">"geospatial_lon_min"</span>], ds_shark.attrs[<span class="st">"geospatial_lon_max"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Temporal and spatial ranges of the satellite dataset
time range 2003-01-05T00:00:00Z 2022-06-14T00:00:00Z
latitude range -89.97917 89.97916
longitude range -179.9792 179.9792</code></pre>
</div>
</div>
</section>
<section id="match-each-shark-detection-to-a-local-satellite-window-0.2" class="level2">
<h2 class="anchored" data-anchor-id="match-each-shark-detection-to-a-local-satellite-window-0.2">Match each shark detection to a local satellite window (±0.2°)</h2>
<p>This function matches a single shark detection to satellite chlorophyll by selecting the nearest satellite time and extracting a ±0.2° spatial window. It summarizes local conditions by computing the mean, standard deviation, and number of valid pixels.</p>
<div id="cell-38" class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> match_one_point(ds, lon, lat, req_time, half_window<span class="op">=</span><span class="fl">0.2</span>):</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Match a single telemetry detection to satellite chlorophyll using</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co">    spatial averaging within a local window.</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co">    For a given longitude, latitude, and detection time, this function:</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="co">    selects the nearest satellite time, extracts chlorophyll pixels within</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="co">    a ±half_window degree box around the detection, and summarizes local</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="co">    conditions using the mean, standard deviation, and number of valid pixels.</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="co">    ----------</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a><span class="co">    ds : xarray.Dataset</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a><span class="co">        ERDDAP gridded satellite dataset opened via Xarray/OPeNDAP.</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a><span class="co">    lon : float</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a><span class="co">        Longitude of the telemetry detection (decimal degrees).</span></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="co">    lat : float</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a><span class="co">        Latitude of the telemetry detection (decimal degrees).</span></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a><span class="co">    req_time : datetime-like</span></span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a><span class="co">        Telemetry detection time; the nearest satellite time is used.</span></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a><span class="co">    half_window : float, optional</span></span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a><span class="co">        Half-width of the spatial averaging window in degrees (default 0.2).</span></span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns</span></span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a><span class="co">    -------</span></span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a><span class="co">    dict</span></span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a><span class="co">        Dictionary containing mean chlorophyll, standard deviation, number</span></span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a><span class="co">        of valid pixels, the matched satellite time, spatial window bounds,</span></span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a><span class="co">        and the original detection time.</span></span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Nearest satellite time</span></span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>    ds_time <span class="op">=</span> ds.sel(time<span class="op">=</span>req_time, method<span class="op">=</span><span class="st">"nearest"</span>)</span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a>    sat_time <span class="op">=</span> pd.to_datetime(ds_time.time.values)</span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Spatial bounds</span></span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a>    lon_min <span class="op">=</span> lon <span class="op">-</span> half_window</span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a>    lon_max <span class="op">=</span> lon <span class="op">+</span> half_window</span>
<span id="cb25-38"><a href="#cb25-38" aria-hidden="true" tabindex="-1"></a>    lat_min <span class="op">=</span> lat <span class="op">-</span> half_window</span>
<span id="cb25-39"><a href="#cb25-39" aria-hidden="true" tabindex="-1"></a>    lat_max <span class="op">=</span> lat <span class="op">+</span> half_window</span>
<span id="cb25-40"><a href="#cb25-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-41"><a href="#cb25-41" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Latitude often runs descending in ERDDAP products</span></span>
<span id="cb25-42"><a href="#cb25-42" aria-hidden="true" tabindex="-1"></a>    chl <span class="op">=</span> ds_time[<span class="st">"chlorophyll"</span>].sel(</span>
<span id="cb25-43"><a href="#cb25-43" aria-hidden="true" tabindex="-1"></a>        longitude<span class="op">=</span><span class="bu">slice</span>(lon_min, lon_max),</span>
<span id="cb25-44"><a href="#cb25-44" aria-hidden="true" tabindex="-1"></a>        latitude<span class="op">=</span><span class="bu">slice</span>(lat_max, lat_min)</span>
<span id="cb25-45"><a href="#cb25-45" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb25-46"><a href="#cb25-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-47"><a href="#cb25-47" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {</span>
<span id="cb25-48"><a href="#cb25-48" aria-hidden="true" tabindex="-1"></a>        <span class="st">"mean_chlorophyll"</span>: <span class="bu">float</span>(chl.mean(skipna<span class="op">=</span><span class="va">True</span>)),</span>
<span id="cb25-49"><a href="#cb25-49" aria-hidden="true" tabindex="-1"></a>        <span class="st">"stdev_chlorophyll"</span>: <span class="bu">float</span>(chl.std(skipna<span class="op">=</span><span class="va">True</span>)),</span>
<span id="cb25-50"><a href="#cb25-50" aria-hidden="true" tabindex="-1"></a>        <span class="st">"n"</span>: <span class="bu">int</span>(chl.count()),</span>
<span id="cb25-51"><a href="#cb25-51" aria-hidden="true" tabindex="-1"></a>        <span class="st">"satellite_date"</span>: sat_time,</span>
<span id="cb25-52"><a href="#cb25-52" aria-hidden="true" tabindex="-1"></a>        <span class="st">"requested_lon_min"</span>: lon_min,</span>
<span id="cb25-53"><a href="#cb25-53" aria-hidden="true" tabindex="-1"></a>        <span class="st">"requested_lon_max"</span>: lon_max,</span>
<span id="cb25-54"><a href="#cb25-54" aria-hidden="true" tabindex="-1"></a>        <span class="st">"requested_lat_min"</span>: lat_min,</span>
<span id="cb25-55"><a href="#cb25-55" aria-hidden="true" tabindex="-1"></a>        <span class="st">"requested_lat_max"</span>: lat_max,</span>
<span id="cb25-56"><a href="#cb25-56" aria-hidden="true" tabindex="-1"></a>        <span class="st">"requested_date"</span>: pd.to_datetime(req_time),</span>
<span id="cb25-57"><a href="#cb25-57" aria-hidden="true" tabindex="-1"></a>    }</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="run-the-matchup-for-all-shark-detections" class="level2">
<h2 class="anchored" data-anchor-id="run-the-matchup-for-all-shark-detections">Run the matchup for all shark detections</h2>
<div id="cell-40" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the matchup for every point:</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>half_window <span class="op">=</span> <span class="fl">0.2</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> [</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    match_one_point(ds_shark, lon, lat, t, half_window<span class="op">=</span>half_window)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> lon, lat, t <span class="kw">in</span> <span class="bu">zip</span>(xcoord, ycoord, tcoord)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>shark_matchups <span class="op">=</span> pd.DataFrame.from_records(rows)</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>shark_matchups.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">mean_chlorophyll</th>
<th data-quarto-table-cell-role="th">stdev_chlorophyll</th>
<th data-quarto-table-cell-role="th">n</th>
<th data-quarto-table-cell-role="th">satellite_date</th>
<th data-quarto-table-cell-role="th">requested_lon_min</th>
<th data-quarto-table-cell-role="th">requested_lon_max</th>
<th data-quarto-table-cell-role="th">requested_lat_min</th>
<th data-quarto-table-cell-role="th">requested_lat_max</th>
<th data-quarto-table-cell-role="th">requested_date</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>3.600632</td>
<td>1.796631</td>
<td>62</td>
<td>2017-09-18</td>
<td>-75.234180</td>
<td>-74.834180</td>
<td>38.025030</td>
<td>38.425030</td>
<td>2017-09-15</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>3.486308</td>
<td>1.330631</td>
<td>62</td>
<td>2017-09-26</td>
<td>-75.211660</td>
<td>-74.811660</td>
<td>38.108900</td>
<td>38.508900</td>
<td>2017-09-27</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>5.782278</td>
<td>3.086404</td>
<td>67</td>
<td>2017-10-04</td>
<td>-75.211660</td>
<td>-74.811660</td>
<td>38.108900</td>
<td>38.508900</td>
<td>2017-10-02</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>1.374190</td>
<td>0.879763</td>
<td>16</td>
<td>2017-10-12</td>
<td>-74.976897</td>
<td>-74.576897</td>
<td>38.474039</td>
<td>38.874039</td>
<td>2017-10-08</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>0.864735</td>
<td>0.149003</td>
<td>24</td>
<td>2017-10-12</td>
<td>-74.860156</td>
<td>-74.460156</td>
<td>38.324397</td>
<td>38.724397</td>
<td>2017-10-09</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="assemble-a-consolidated-telemetrysatellite-dataset" class="level2">
<h2 class="anchored" data-anchor-id="assemble-a-consolidated-telemetrysatellite-dataset">Assemble a consolidated telemetry–satellite dataset</h2>
<p>Telemetry coordinates, transmitter IDs, and matched chlorophyll values are combined into a single DataFrame. This unified table is used for all subsequent mapping and analysis steps.</p>
<div id="cell-42" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>alltags <span class="op">=</span> pd.DataFrame({</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"lon"</span>: xcoord,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"lat"</span>: ycoord,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"chlorophyll"</span>: shark_matchups[<span class="st">"mean_chlorophyll"</span>].to_numpy(),</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"transmitter"</span>: tags[<span class="st">"Transmitter"</span>].to_numpy(),</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"date"</span>: shark_matchups[<span class="st">"requested_date"</span>].to_numpy(),</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(alltags.shape)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>alltags.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(417, 5)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">lon</th>
<th data-quarto-table-cell-role="th">lat</th>
<th data-quarto-table-cell-role="th">chlorophyll</th>
<th data-quarto-table-cell-role="th">transmitter</th>
<th data-quarto-table-cell-role="th">date</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>-75.034180</td>
<td>38.225030</td>
<td>3.600632</td>
<td>A69-1601-46065</td>
<td>2017-09-15</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>-75.011660</td>
<td>38.308900</td>
<td>3.486308</td>
<td>A69-1601-46065</td>
<td>2017-09-27</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>-75.011660</td>
<td>38.308900</td>
<td>5.782278</td>
<td>A69-1601-46065</td>
<td>2017-10-02</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>-74.776897</td>
<td>38.674039</td>
<td>1.374190</td>
<td>A69-1601-46065</td>
<td>2017-10-08</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>-74.660156</td>
<td>38.524397</td>
<td>0.864735</td>
<td>A69-1601-46065</td>
<td>2017-10-09</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="map-of-all-sharks-colored-by-chlorophyll" class="level2">
<h2 class="anchored" data-anchor-id="map-of-all-sharks-colored-by-chlorophyll">Map of all sharks colored by chlorophyll</h2>
<p>Plot the locations of all tagged dusky sharks and color each detection by the mean satellite-derived chlorophyll-a concentration matched to that location and date.</p>
<p>Each point represents a single shark detection, and the color scale highlights spatial differences in chlorophyll conditions encountered by sharks across the study area. A simple land mask and coastline provide geographic context, while latitude and longitude gridlines help orient the map.</p>
<p>This visualization provides a spatial overview of shark movements in relation to surface ocean productivity.</p>
<div id="cell-44" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">8</span>))</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> plt.axes(projection<span class="op">=</span>ccrs.PlateCarree())</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>ax.add_feature(cfeature.LAND, facecolor<span class="op">=</span><span class="st">"lightgray"</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>ax.add_feature(cfeature.COASTLINE)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>sc <span class="op">=</span> ax.scatter(</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>    alltags[<span class="st">"lon"</span>],</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>    alltags[<span class="st">"lat"</span>],</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>    c<span class="op">=</span>alltags[<span class="st">"chlorophyll"</span>],</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>    cmap<span class="op">=</span><span class="st">"YlGn"</span>,</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>    s<span class="op">=</span><span class="dv">20</span>,</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>    transform<span class="op">=</span>ccrs.PlateCarree()</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>plt.colorbar(sc, label<span class="op">=</span><span class="st">"Chl-a (mg m$^{-3}$)"</span>)</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>gl <span class="op">=</span> ax.gridlines(</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>    draw_labels<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>    linewidth<span class="op">=</span><span class="fl">0.5</span>,</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"gray"</span>,</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>    alpha<span class="op">=</span><span class="fl">0.7</span>,</span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>    linestyle<span class="op">=</span><span class="st">"--"</span></span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>gl.top_labels <span class="op">=</span> <span class="va">False</span></span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>gl.right_labels <span class="op">=</span> <span class="va">False</span></span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>gl.xformatter <span class="op">=</span> LONGITUDE_FORMATTER</span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a>gl.yformatter <span class="op">=</span> LATITUDE_FORMATTER</span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Mean chlorophyll at dusky shark locations"</span>)</span>
<span id="cb29-31"><a href="#cb29-31" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="satellite_matchups_to_track_locations_xarray_files/figure-html/cell-20-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="subset-all-tags-for-a-single-shark" class="level2">
<h2 class="anchored" data-anchor-id="subset-all-tags-for-a-single-shark">Subset all tags for a single shark</h2>
<p>This step selects all detections associated with one transmitter ID. Focusing on a single shark allows individual movement patterns and environmental conditions to be examined.</p>
<div id="cell-46" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>shark1 <span class="op">=</span> alltags[<span class="st">"transmitter"</span>].iloc[<span class="dv">0</span>]</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Selected shark transmitter:"</span>, shark1)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>single_shark <span class="op">=</span> alltags.loc[alltags[<span class="st">"transmitter"</span>] <span class="op">==</span> shark1, [<span class="st">"lon"</span>, <span class="st">"lat"</span>, <span class="st">"chlorophyll"</span>]].copy()</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>single_shark.columns <span class="op">=</span> [<span class="st">"x_shark"</span>, <span class="st">"y_shark"</span>, <span class="st">"dataval_shark"</span>]</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>single_shark.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Selected shark transmitter: A69-1601-46065</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">x_shark</th>
<th data-quarto-table-cell-role="th">y_shark</th>
<th data-quarto-table-cell-role="th">dataval_shark</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>-75.034180</td>
<td>38.225030</td>
<td>3.600632</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>-75.011660</td>
<td>38.308900</td>
<td>3.486308</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>-75.011660</td>
<td>38.308900</td>
<td>5.782278</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>-74.776897</td>
<td>38.674039</td>
<td>1.374190</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>-74.660156</td>
<td>38.524397</td>
<td>0.864735</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="plot-the-movement-track-for-a-single-shark" class="level2">
<h2 class="anchored" data-anchor-id="plot-the-movement-track-for-a-single-shark">Plot the movement track for a single shark</h2>
<p>Successive detections for one shark are connected with track lines and colored by chlorophyll concentration. This combined view highlights both movement pathways and changing environmental conditions along the track.</p>
<div id="cell-48" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> single_shark[<span class="st">"x_shark"</span>].to_numpy()</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> single_shark[<span class="st">"y_shark"</span>].to_numpy()</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>chl <span class="op">=</span> single_shark[<span class="st">"dataval_shark"</span>].to_numpy()</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>pad <span class="op">=</span> <span class="fl">0.5</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>maplonmin <span class="op">=</span> x.<span class="bu">min</span>() <span class="op">-</span> pad</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>maplonmax <span class="op">=</span> x.<span class="bu">max</span>() <span class="op">+</span> pad</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>maplatmin <span class="op">=</span> y.<span class="bu">min</span>() <span class="op">-</span> pad</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>maplatmax <span class="op">=</span> y.<span class="bu">max</span>() <span class="op">+</span> pad</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">8</span>))</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> plt.axes(projection<span class="op">=</span>ccrs.PlateCarree())</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>ax.add_feature(cfeature.LAND, facecolor<span class="op">=</span><span class="st">"lightgrey"</span>)</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>ax.add_feature(cfeature.COASTLINE)</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>ax.set_extent([maplonmin, maplonmax, maplatmin, maplatmax], crs<span class="op">=</span>ccrs.PlateCarree())</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Track polyline</span></span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>ax.plot(</span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>    x, y,</span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"black"</span>,</span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>    linewidth<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a>    alpha<span class="op">=</span><span class="fl">0.7</span>,</span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a>    transform<span class="op">=</span>ccrs.PlateCarree()</span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter points</span></span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a>sc <span class="op">=</span> ax.scatter(</span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a>    x, y,</span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a>    c<span class="op">=</span>chl,</span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a>    cmap<span class="op">=</span><span class="st">"YlGn"</span>,</span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a>    s<span class="op">=</span><span class="dv">25</span>,</span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a>    transform<span class="op">=</span>ccrs.PlateCarree(),</span>
<span id="cb32-35"><a href="#cb32-35" aria-hidden="true" tabindex="-1"></a>    zorder<span class="op">=</span><span class="dv">3</span></span>
<span id="cb32-36"><a href="#cb32-36" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-37"><a href="#cb32-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-38"><a href="#cb32-38" aria-hidden="true" tabindex="-1"></a>gl <span class="op">=</span> ax.gridlines(draw_labels<span class="op">=</span><span class="va">True</span>, linewidth<span class="op">=</span><span class="fl">0.5</span>, color<span class="op">=</span><span class="st">"gray"</span>, alpha<span class="op">=</span><span class="fl">0.7</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb32-39"><a href="#cb32-39" aria-hidden="true" tabindex="-1"></a>gl.top_labels <span class="op">=</span> <span class="va">False</span></span>
<span id="cb32-40"><a href="#cb32-40" aria-hidden="true" tabindex="-1"></a>gl.right_labels <span class="op">=</span> <span class="va">False</span></span>
<span id="cb32-41"><a href="#cb32-41" aria-hidden="true" tabindex="-1"></a>gl.xformatter <span class="op">=</span> LONGITUDE_FORMATTER</span>
<span id="cb32-42"><a href="#cb32-42" aria-hidden="true" tabindex="-1"></a>gl.yformatter <span class="op">=</span> LATITUDE_FORMATTER</span>
<span id="cb32-43"><a href="#cb32-43" aria-hidden="true" tabindex="-1"></a>gl.xlabel_style <span class="op">=</span> {<span class="st">"size"</span>: <span class="dv">9</span>}</span>
<span id="cb32-44"><a href="#cb32-44" aria-hidden="true" tabindex="-1"></a>gl.ylabel_style <span class="op">=</span> {<span class="st">"size"</span>: <span class="dv">9</span>}</span>
<span id="cb32-45"><a href="#cb32-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-46"><a href="#cb32-46" aria-hidden="true" tabindex="-1"></a>cbar <span class="op">=</span> plt.colorbar(sc, ax<span class="op">=</span>ax)</span>
<span id="cb32-47"><a href="#cb32-47" aria-hidden="true" tabindex="-1"></a>cbar.set_label(<span class="st">"Chl-a (mg m$^{-3}$)"</span>)</span>
<span id="cb32-48"><a href="#cb32-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-49"><a href="#cb32-49" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Mean chl-a values for dusky shark #1 (with tracks)"</span>)</span>
<span id="cb32-50"><a href="#cb32-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-51"><a href="#cb32-51" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb32-52"><a href="#cb32-52" aria-hidden="true" tabindex="-1"></a>plt.close(fig)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="satellite_matchups_to_track_locations_xarray_files/figure-html/cell-22-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="compare-chlorophyll-conditions-by-year-using-a-boxplot" class="level2">
<h2 class="anchored" data-anchor-id="compare-chlorophyll-conditions-by-year-using-a-boxplot">Compare chlorophyll conditions by year using a boxplot</h2>
<p>Matched chlorophyll values for a single shark are grouped by calendar year and displayed as a boxplot. The boxplot summarizes interannual differences and variability in environmental conditions experienced by the shark.</p>
<div id="cell-50" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="op">=</span> alltags.loc[alltags[<span class="st">"transmitter"</span>] <span class="op">==</span> shark1, [<span class="st">"date"</span>, <span class="st">"chlorophyll"</span>]].dropna()</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>df1[<span class="st">"year"</span>] <span class="op">=</span> pd.to_datetime(df1[<span class="st">"date"</span>]).dt.year</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>vals_2017 <span class="op">=</span> df1.loc[df1[<span class="st">"year"</span>] <span class="op">==</span> <span class="dv">2017</span>, <span class="st">"chlorophyll"</span>].to_numpy()</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>vals_2018 <span class="op">=</span> df1.loc[df1[<span class="st">"year"</span>] <span class="op">==</span> <span class="dv">2018</span>, <span class="st">"chlorophyll"</span>].to_numpy()</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">6</span>))</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>ax.boxplot(</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>    [vals_2017, vals_2018],</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>    positions<span class="op">=</span>[<span class="dv">1</span>, <span class="dv">2</span>],</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>    patch_artist<span class="op">=</span><span class="va">True</span>,                      <span class="co"># allow filled boxes</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>    boxprops<span class="op">=</span><span class="bu">dict</span>(facecolor<span class="op">=</span><span class="st">"green"</span>, alpha<span class="op">=</span><span class="fl">0.7</span>),</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>    medianprops<span class="op">=</span><span class="bu">dict</span>(color<span class="op">=</span><span class="st">"black"</span>),</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>    whiskerprops<span class="op">=</span><span class="bu">dict</span>(color<span class="op">=</span><span class="st">"black"</span>),</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>    capprops<span class="op">=</span><span class="bu">dict</span>(color<span class="op">=</span><span class="st">"black"</span>)</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Chlorophyll conditions for a single dusky shark"</span>)</span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Year"</span>)</span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Chl-a (mg m$^{-3}$)"</span>)</span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a>ax.set_xticks([<span class="dv">1</span>, <span class="dv">2</span>])</span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a>ax.set_xticklabels([<span class="st">"2017"</span>, <span class="st">"2018"</span>])</span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="satellite_matchups_to_track_locations_xarray_files/figure-html/cell-23-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© CC-By CoastWatch, 2026</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>